const vocabularySets = [
    {
        name: '파고다 JLPT 최빈출 한자 어휘',
        words: [
            { id: '1_1', japanese: "飽きる", reading: "あきる", meaning: "질리다, 싫증나다" },
            { id: '1_2', japanese: "預ける", reading: "あずける", meaning: "맡기다" },
            { id: '1_3', japanese: "当たる", reading: "あたる", meaning: "맞다, 적중하다" },
            { id: '1_4', japanese: "余る", reading: "あまる", meaning: "남다" },
            { id: '1_5', japanese: "編む", reading: "あむ", meaning: "(스웨터를) 짜다" },
            { id: '1_6', japanese: "表す", reading: "あらわす", meaning: "나타내다, 표현하다" },
            { id: '1_7', japanese: "慌てる", reading: "あわてる", meaning: "허둥대다" },
            { id: '1_8', japanese: "急ぐ", reading: "いそぐ", meaning: "서두르다" },
            { id: '1_9', japanese: "挑む", reading: "いどむ", meaning: "도전하다" },
            { id: '1_10', japanese: "植える", reading: "うえる", meaning: "심다" },
            { id: '1_11', japanese: "受け取る", reading: "うけとる", meaning: "수취하다, 받다" },
            { id: '1_12', japanese: "疑う", reading: "うたがう", meaning: "의심하다" },
            { id: '1_13', japanese: "打つ", reading: "うつ", meaning: "치다" },
            { id: '1_14', japanese: "移る", reading: "うつる", meaning: "옮다, 이동하다" },
            { id: '1_15', japanese: "奪う", reading: "うばう", meaning: "빼앗다" },
            { id: '1_16', japanese: "埋める", reading: "うめる", meaning: "묻다, 메우다, 채우다" },
            { id: '1_17', japanese: "売り切れる", reading: "うりきれる", meaning: "다 팔리다, 매진되다" },
            { id: '1_18', japanese: "追いつく", reading: "おいつく", meaning: "따라잡다" },
            { id: '1_19', japanese: "抑える", reading: "おさえる", meaning: "(감정, 요구를) 억제하다, (소비, 지출을) 줄이다" },
            { id: '1_20', japanese: "押す", reading: "おす", meaning: "누르다, 밀다" },
            { id: '1_21', japanese: "落ち着く", reading: "おちつく", meaning: "침착하다, 차분해지다" },
            { id: '1_22', japanese: "驚く", reading: "おどろく", meaning: "놀라다" },
            { id: '1_23', japanese: "覚える", reading: "おぼえる", meaning: "외우다, 기억하다" },
            { id: '1_24', japanese: "折る", reading: "おる", meaning: "꺾다, 접다" },
            { id: '1_25', japanese: "折れる", reading: "おれる", meaning: "꺾이다, 접히다" },
            { id: '1_26', japanese: "替える", reading: "かえる", meaning: "바꾸다, 교환하다" },
            { id: '1_27', japanese: "輝く", reading: "かがやく", meaning: "빛나다" },
            { id: '1_28', japanese: "隠す", reading: "かくす", meaning: "숨기다" },
            { id: '1_29', japanese: "駆ける", reading: "かける", meaning: "전속력으로 달리다, 뛰다" },
            { id: '1_30', japanese: "囲む", reading: "かこむ", meaning: "둘러싸다" },
            { id: '1_31', japanese: "重ねる", reading: "かさねる", meaning: "겹치다, 포개다, 거듭하다" },
            { id: '1_32', japanese: "飾る", reading: "かざる", meaning: "장식하다" },
            { id: '1_33', japanese: "貸す", reading: "かす", meaning: "빌려주다" },
            { id: '1_34', japanese: "借りる", reading: "かりる", meaning: "빌리다" },
            { id: '1_35', japanese: "枯れる", reading: "かれる", meaning: "시들다" },
            { id: '1_36', japanese: "乾く", reading: "かわく", meaning: "마르다, 건조되다" },
            { id: '1_37', japanese: "消える", reading: "きえる", meaning: "꺼지다, 사라지다" },
            { id: '1_38', japanese: "嫌う", reading: "きらう", meaning: "싫어하다" },
            { id: '1_39', japanese: "配る", reading: "くばる", meaning: "나눠주다" },
            { id: '1_40', japanese: "組み立てる", reading: "くみたてる", meaning: "조립하다" },
            { id: '1_41', japanese: "組む", reading: "くむ", meaning: "짜다, (팔짱을) 끼다" },
            { id: '1_42', japanese: "繰り返す", reading: "くりかえす", meaning: "반복하다" },
            { id: '1_43', japanese: "加える", reading: "くわえる", meaning: "더하다, 추가하다" },
            { id: '1_44', japanese: "消す", reading: "けす", meaning: "끄다, 지우다" },
            { id: '1_45', japanese: "凍る", reading: "こおる", meaning: "얼다" },
            { id: '1_46', japanese: "焦げる", reading: "こげる", meaning: "(음식이) 타다, 눌어붙다" },
            { id: '1_47', japanese: "断る", reading: "ことわる", meaning: "거절하다" },
            { id: '1_48', japanese: "転ぶ", reading: "ころぶ", meaning: "구르다, 넘어지다" },
            { id: '1_49', japanese: "怖がる", reading: "こわがる", meaning: "무서워하다" },
            { id: '1_50', japanese: "覚める", reading: "さめる", meaning: "(눈이) 떠지다" },
            { id: '1_51', japanese: "騒ぐ", reading: "さわぐ", meaning: "떠들다, 소란 피우다" },
            { id: '1_52', japanese: "触る", reading: "さわる", meaning: "만지다" },
            { id: '1_53', japanese: "沈む", reading: "しずむ", meaning: "가라앉다" },
            { id: '1_54', japanese: "従う", reading: "したがう", meaning: "따르다" },
            { id: '1_55', japanese: "縛る", reading: "しばる", meaning: "(끈으로) 묶다" },
            { id: '1_56', japanese: "絞る", reading: "しぼる", meaning: "(물기를) 짜다, (범위를) 줄이다" },
            { id: '1_57', japanese: "示す", reading: "しめす", meaning: "나타내다, 제시하다" },
            { id: '1_58', japanese: "締める", reading: "しめる", meaning: "바싹 졸라 메다" },
            { id: '1_59', japanese: "信じる", reading: "しんじる", meaning: "믿다" },
            { id: '1_60', japanese: "過ぎる", reading: "すぎる", meaning: "지나다" },
            { id: '1_61', japanese: "捨てる", reading: "すてる", meaning: "버리다" },
            { id: '1_62', japanese: "育てる", reading: "そだてる", meaning: "키우다" },
            { id: '1_63', japanese: "倒れる", reading: "たおれる", meaning: "쓰러지다, 넘어지다" },
            { id: '1_64', japanese: "確かめる", reading: "たしかめる", meaning: "확인하다" },
            { id: '1_65', japanese: "戦う", reading: "たたかう", meaning: "싸우다" },
            { id: '1_66', japanese: "畳む", reading: "たたむ", meaning: "(빨래를) 개다" },
            { id: '1_67', japanese: "経つ", reading: "たつ", meaning: "(시간이) 흐르다, 경과하다" },
            { id: '1_68', japanese: "黙る", reading: "だまる", meaning: "입 다물다" },
            { id: '1_69', japanese: "頼る", reading: "たよる", meaning: "의지하다, 기대다" },
            { id: '1_70', japanese: "違う", reading: "ちがう", meaning: "다르다" },
            { id: '1_71', japanese: "疲れる", reading: "つかれる", meaning: "피곤하다" },
            { id: '1_72', japanese: "伝わる", reading: "つたわる", meaning: "전해지다" },
            { id: '1_73', japanese: "包む", reading: "つつむ", meaning: "싸다, 포장하다" },
            { id: '1_74', japanese: "勤める", reading: "つとめる", meaning: "근무하다" },
            { id: '1_75', japanese: "通る", reading: "とおる", meaning: "통과하다, 지나가다" },
            { id: '1_76', japanese: "解ける", reading: "とける", meaning: "(문제가) 풀리다, 해결되다" },
            { id: '1_77', japanese: "溶ける", reading: "とける", meaning: "녹다" },
            { id: '1_78', japanese: "閉じる", reading: "とじる", meaning: "(눈을) 감다, (책을) 덮다" },
            { id: '1_79', japanese: "怒鳴る", reading: "どなる", meaning: "고함치다, 호통치다" },
            { id: '1_80', japanese: "飛ぶ", reading: "とぶ", meaning: "날다" },
            { id: '1_81', japanese: "取り消す", reading: "とりけす", meaning: "취소하다" },
            { id: '1_82', japanese: "流れる", reading: "ながれる", meaning: "흐르다" },
            { id: '1_83', japanese: "泣く", reading: "なく", meaning: "울다" },
            { id: '1_84', japanese: "慰める", reading: "なぐさめる", meaning: "위로하다" },
            { id: '1_85', japanese: "投げる", reading: "なげる", meaning: "던지다" },
            { id: '1_86', japanese: "並ぶ", reading: "ならぶ", meaning: "한 줄로 서다, 늘어서다" },
            { id: '1_87', japanese: "似合う", reading: "にあう", meaning: "어울리다" },
            { id: '1_88', japanese: "握る", reading: "にぎる", meaning: "(손에 꽉) 쥐다" },
            { id: '1_89', japanese: "逃げる", reading: "にげる", meaning: "도망치다" },
            { id: '1_90', japanese: "濡れる", reading: "ぬれる", meaning: "젖다" },
            { id: '1_91', japanese: "願う", reading: "ねがう", meaning: "바라다, 원하다" },
            { id: '1_92', japanese: "眠る", reading: "ねむる", meaning: "잠들다, 자다" },
            { id: '1_93', japanese: "残る", reading: "のこる", meaning: "남다" },
            { id: '1_94', japanese: "延ばす", reading: "のばす", meaning: "(시일을) 연장시키다, 미루다" },
            { id: '1_95', japanese: "生える", reading: "はえる", meaning: "(수염, 풀 등이) 나다, 자라다" },
            { id: '1_96', japanese: "測る", reading: "はかる", meaning: "(길이, 높이, 속도 등을) 측정하다" },
            { id: '1_97', japanese: "量る", reading: "はかる", meaning: "(무게, 중량 등을) 측정하다" },
            { id: '1_98', japanese: "運ぶ", reading: "はこぶ", meaning: "운반하다" },
            { id: '1_99', japanese: "離す", reading: "はなす", meaning: "떼다, 놓치다" },
            { id: '1_100', japanese: "冷える", reading: "ひえる", meaning: "차가워지다" },
            { id: '1_101', japanese: "光る", reading: "ひかる", meaning: "빛나다" },
            { id: '1_102', japanese: "引き受ける", reading: "ひきうける", meaning: "받아들이다" },
            { id: '1_103', japanese: "拾う", reading: "ひろう", meaning: "줍다" },
            { id: '1_104', japanese: "拭く", reading: "ふく", meaning: "닦다" },
            { id: '1_105', japanese: "防ぐ", reading: "ふせぐ", meaning: "막다, 방지하다" },
            { id: '1_106', japanese: "触れる", reading: "ふれる", meaning: "<자동사> 닿다 <타동사> 만지다" },
            { id: '1_107', japanese: "干す", reading: "ほす", meaning: "말리다, 건조시키다, 널다" },
            { id: '1_108', japanese: "曲げる", reading: "まげる", meaning: "구부리다" },
            { id: '1_109', japanese: "混ぜる", reading: "まぜる", meaning: "섞다" },
            { id: '1_110', japanese: "待ち合わせる", reading: "まちあわせる", meaning: "(장소, 시간을 정하고) 만나기로 하다" },
            { id: '1_111', japanese: "学ぶ", reading: "まなぶ", meaning: "배우다" },
            { id: '1_112', japanese: "間に合う", reading: "まにあう", meaning: "시간에 대다, 시간에 맞추다" },
            { id: '1_113', japanese: "守る", reading: "まもる", meaning: "지키다" },
            { id: '1_114', japanese: "回す", reading: "まわす", meaning: "돌리다" },
            { id: '1_115', japanese: "見つける", reading: "みつける", meaning: "발견하다, 찾다" },
            { id: '1_116', japanese: "結ぶ", reading: "むすぶ", meaning: "잇다, 묶다, 맺다" },
            { id: '1_117', japanese: "申し込む", reading: "もうしこむ", meaning: "신청하다" },
            { id: '1_118', japanese: "燃える", reading: "もえる", meaning: "타다" },
            { id: '1_119', japanese: "焼く", reading: "やく", meaning: "굽다" },
            { id: '1_120', japanese: "破る", reading: "やぶる", meaning: "깨다, 찢다, 어기다" },
            { id: '1_121', japanese: "破れる", reading: "やぶれる", meaning: "깨지다, 찢어지다" },
            { id: '1_122', japanese: "許す", reading: "ゆるす", meaning: "허락하다, 용서하다" },
            { id: '1_123', japanese: "揺れる", reading: "ゆれる", meaning: "흔들리다" },
            { id: '1_124', japanese: "汚れる", reading: "よごれる", meaning: "더러워지다" },
            { id: '1_125', japanese: "呼びかける", reading: "よびかける", meaning: "호소하다, 당부하다" },
            { id: '1_126', japanese: "渡す", reading: "わたす", meaning: "건네다" },
            { id: '1_127', japanese: "割れる", reading: "われる", meaning: "나뉘다, 깨지다" },
            { id: '1_128', japanese: "浅い", reading: "あさい", meaning: "얕다" },
            { id: '1_129', japanese: "厚い", reading: "あつい", meaning: "두껍다" },
            { id: '1_130', japanese: "甘い", reading: "あまい", meaning: "달다, 엄하지 않다" },
            { id: '1_131', japanese: "怪しい", reading: "あやしい", meaning: "수상하다" },
            { id: '1_132', japanese: "薄い", reading: "うすい", meaning: "얇다, 엷다" },
            { id: '1_133', japanese: "美しい", reading: "うつくしい", meaning: "아름답다" },
            { id: '1_134', japanese: "偉い", reading: "えらい", meaning: "훌륭하다, 위대하다" },
            { id: '1_135', japanese: "惜しい", reading: "おしい", meaning: "아깝다, 애석하다" },
            { id: '1_136', japanese: "悲しい", reading: "かなしい", meaning: "슬프다" },
            { id: '1_137', japanese: "辛い", reading: "からい", meaning: "맵다" },
            { id: '1_138', japanese: "汚い", reading: "きたない", meaning: "더럽다, 지저분하다" },
            { id: '1_139', japanese: "厳しい", reading: "きびしい", meaning: "엄격하다" },
            { id: '1_140', japanese: "暗い", reading: "くらい", meaning: "어둡다" },
            { id: '1_141', japanese: "苦しい", reading: "くるしい", meaning: "힘들다" },
            { id: '1_142', japanese: "詳しい", reading: "くわしい", meaning: "자세하다, 상세하다, 잘 알고 있다" },
            { id: '1_143', japanese: "恋しい", reading: "こいしい", meaning: "그립다" },
            { id: '1_144', japanese: "細かい", reading: "こまかい", meaning: "잘다, 작다, 세세하다" },
            { id: '1_145', japanese: "親しい", reading: "したしい", meaning: "친하다" },
            { id: '1_146', japanese: "懐かしい", reading: "なつかしい", meaning: "그립다" },
            { id: '1_147', japanese: "深い", reading: "ふかい", meaning: "깊다" },
            { id: '1_148', japanese: "細い", reading: "ほそい", meaning: "가늘다" },
            { id: '1_149', japanese: "貧しい", reading: "まずしい", meaning: "가난하다" },
            { id: '1_150', japanese: "丸い", reading: "まるい", meaning: "둥글다" },
            { id: '1_151', japanese: "短い", reading: "みじかい", meaning: "짧다" },
            { id: '1_152', japanese: "易しい", reading: "やさしい", meaning: "쉽다" },
            { id: '1_153', japanese: "優しい", reading: "やさしい", meaning: "상냥하다" },
            { id: '1_154', japanese: "緩い", reading: "ゆるい", meaning: "느슨하다, 엄하지 않다" },
            { id: '1_155', japanese: "若い", reading: "わかい", meaning: "젊다" },
            { id: '1_156', japanese: "一般的だ", reading: "いっぱんてきだ", meaning: "일반적이다" },
            { id: '1_157', japanese: "主だ", reading: "おもだ", meaning: "주되다" },
            { id: '1_158', japanese: "確実だ", reading: "かくじつだ", meaning: "확실하다" },
            { id: '1_159', japanese: "感情的だ", reading: "かんじょうてきだ", meaning: "감정적이다" },
            { id: '1_160', japanese: "簡単だ", reading: "かんたんだ", meaning: "간단하다" },
            { id: '1_161', japanese: "具体的だ", reading: "ぐたいてきだ", meaning: "구체적이다" },
            { id: '1_162', japanese: "盛んだ", reading: "さかんだ", meaning: "활발하다, 성행하다" },
            { id: '1_163', japanese: "実用的だ", reading: "じつようてきだ", meaning: "실용적이다" },
            { id: '1_164', japanese: "重要だ", reading: "じゅうようだ", meaning: "중요하다" },
            { id: '1_165', japanese: "主要だ", reading: "しゅようだ", meaning: "주요하다" },
            { id: '1_166', japanese: "正直だ", reading: "しょうじきだ", meaning: "정직하다" },
            { id: '1_167', japanese: "新鮮だ", reading: "しんせんだ", meaning: "신선하다" },
            { id: '1_168', japanese: "正確だ", reading: "せいかくだ", meaning: "정확하다" },
            { id: '1_169', japanese: "清潔だ", reading: "せいけつだ", meaning: "청결하다" },
            { id: '1_170', japanese: "積極的だ", reading: "せっきょくてきだ", meaning: "적극적이다" },
            { id: '1_171', japanese: "退屈だ", reading: "たいくつだ", meaning: "따분하다" },
            { id: '1_172', japanese: "代表的だ", reading: "だいひょうてきだ", meaning: "대표적이다" },
            { id: '1_173', japanese: "短気だ", reading: "たんきだ", meaning: "성미가 급하다" },
            { id: '1_174', japanese: "単純だ", reading: "たんじゅんだ", meaning: "단순하다" },
            { id: '1_175', japanese: "得意だ", reading: "とくいだ", meaning: "잘한다, 숙련되다" },
            { id: '1_176', japanese: "苦手だ", reading: "にがてだ", meaning: "서투르다, 질색이다" },
            { id: '1_177', japanese: "派手だ", reading: "はでだ", meaning: "화려하다" },
            { id: '1_178', japanese: "不安だ", reading: "ふぁんだ", meaning: "불안하다" },
            { id: '1_179', japanese: "複雑だ", reading: "ふくざつだ", meaning: "복잡하다" },
            { id: '1_180', japanese: "無事だ", reading: "ぶじだ", meaning: "무사하다" },
            { id: '1_181', japanese: "立派だ", reading: "りっぱだ", meaning: "훌륭하다" },
            { id: '1_182', japanese: "合図", reading: "あいず", meaning: "(눈짓, 몸짓, 손짓, 소리 등의) 신호" },
            { id: '1_183', japanese: "相手", reading: "あいて", meaning: "상대방" },
            { id: '1_184', japanese: "穴", reading: "あな", meaning: "구멍" },
            { id: '1_185', japanese: "油", reading: "あぶら", meaning: "기름" },
            { id: '1_186', japanese: "泡", reading: "あわ", meaning: "거품" },
            { id: '1_187', japanese: "以下", reading: "いか", meaning: "이하" },
            { id: '1_188', japanese: "息", reading: "いき", meaning: "숨, 호흡" },
            { id: '1_189', japanese: "行き先", reading: "いきさき(ゆきさき)", meaning: "목적지, 행선지" },
            { id: '1_190', japanese: "以降", reading: "いこう", meaning: "이후" },
            { id: '1_191', japanese: "意識", reading: "いしき", meaning: "의식" },
            { id: '1_192', japanese: "板", reading: "いた", meaning: "판자, 널빤지" },
            { id: '1_193', japanese: "位置", reading: "いち", meaning: "위치" },
            { id: '1_194', japanese: "一秒", reading: "いちびょう", meaning: "1초" },
            { id: '1_195', japanese: "移転", reading: "いてん", meaning: "이전" },
            { id: '1_196', japanese: "移動", reading: "いどう", meaning: "이동" },
            { id: '1_197', japanese: "印象", reading: "いんしょう", meaning: "인상" },
            { id: '1_198', japanese: "右折", reading: "うせつ", meaning: "우회전" },
            { id: '1_199', japanese: "裏側", reading: "うらがわ", meaning: "뒤쪽, 안쪽" },
            { id: '1_200', japanese: "影響", reading: "えいきょう", meaning: "영향" },
            { id: '1_201', japanese: "栄養", reading: "えいよう", meaning: "영양" },
            { id: '1_202', japanese: "笑顔", reading: "えがお", meaning: "웃는 얼굴" },
            { id: '1_203', japanese: "枝", reading: "えだ", meaning: "가지" },
            { id: '1_204', japanese: "演奏", reading: "えんそう", meaning: "연주" },
            { id: '1_205', japanese: "お祝い", reading: "おいわい", meaning: "축하" },
            { id: '1_206', japanese: "応援", reading: "おうえん", meaning: "응원" },
            { id: '1_207', japanese: "横断", reading: "おうだん", meaning: "횡단" },
            { id: '1_208', japanese: "往復", reading: "おうふく", meaning: "왕복" },
            { id: '1_209', japanese: "応募", reading: "おうぼ", meaning: "응모" },
            { id: '1_210', japanese: "応用", reading: "おうよう", meaning: "응용" },
            { id: '1_211', japanese: "お代わり", reading: "おかわり", meaning: "한 그릇 더 먹음, 리필" },
            { id: '1_212', japanese: "お見舞い", reading: "おみまい", meaning: "병문안" },
            { id: '1_213', japanese: "温泉", reading: "おんせん", meaning: "온천" },
            { id: '1_214', japanese: "会計", reading: "かいけい", meaning: "회계, 계산" },
            { id: '1_215', japanese: "改札(口)", reading: "かいさつ(ぐち)", meaning: "개찰(구)" },
            { id: '1_216', japanese: "回収", reading: "かいしゅう", meaning: "회수" },
            { id: '1_217', japanese: "香り", reading: "かおり", meaning: "향기" },
            { id: '1_218', japanese: "各自", reading: "かくじ", meaning: "각자" },
            { id: '1_219', japanese: "各地", reading: "かくち", meaning: "각지" },
            { id: '1_220', japanese: "確認", reading: "かくにん", meaning: "확인" },
            { id: '1_221', japanese: "過去", reading: "かこ", meaning: "과거" },
            { id: '1_222', japanese: "数", reading: "かず", meaning: "수, 숫자" },
            { id: '1_223', japanese: "下線", reading: "かせん", meaning: "밑줄" },
            { id: '1_224', japanese: "肩", reading: "かた", meaning: "어깨" },
            { id: '1_225', japanese: "形", reading: "かたち", meaning: "형태, 모양" },
            { id: '1_226', japanese: "片方", reading: "かたほう", meaning: "한쪽" },
            { id: '1_227', japanese: "片道", reading: "かたみち", meaning: "편도" },
            { id: '1_228', japanese: "価値", reading: "かち", meaning: "가치" },
            { id: '1_229', japanese: "活気", reading: "かっき", meaning: "활기" },
            { id: '1_230', japanese: "楽器", reading: "がっき", meaning: "악기" },
            { id: '1_231', japanese: "活動", reading: "かつどう", meaning: "활동" },
            { id: '1_232', japanese: "仮定", reading: "かてい", meaning: "가정" },
            { id: '1_233', japanese: "我慢", reading: "がまん", meaning: "참음" },
            { id: '1_234', japanese: "空", reading: "から", meaning: "(내용물이 없이 속이) 빔, 아무것도 없음" },
            { id: '1_235', japanese: "皮", reading: "かわ", meaning: "껍질, 가죽" },
            { id: '1_236', japanese: "間隔", reading: "かんかく", meaning: "간격" },
            { id: '1_237', japanese: "感覚", reading: "かんかく", meaning: "감각" },
            { id: '1_238', japanese: "観客", reading: "かんきゃく", meaning: "관객" },
            { id: '1_239', japanese: "環境", reading: "かんきょう", meaning: "환경" },
            { id: '1_240', japanese: "関係", reading: "かんけい", meaning: "관계" },
            { id: '1_241', japanese: "感激", reading: "かんげき", meaning: "감격" },
            { id: '1_242', japanese: "観光", reading: "かんこう", meaning: "관광" },
            { id: '1_243', japanese: "観察", reading: "かんさつ", meaning: "관찰" },
            { id: '1_244', japanese: "関心", reading: "かんしん", meaning: "관심" },
            { id: '1_245', japanese: "完成", reading: "かんせい", meaning: "완성" },
            { id: '1_246', japanese: "機械", reading: "きかい", meaning: "기계" },
            { id: '1_247', japanese: "機会", reading: "きかい", meaning: "기회" },
            { id: '1_248', japanese: "期限", reading: "きげん", meaning: "기한" },
            { id: '1_249', japanese: "技術", reading: "ぎじゅつ", meaning: "기술" },
            { id: '1_250', japanese: "傷", reading: "きず", meaning: "상처" },
            { id: '1_251', japanese: "基礎", reading: "きそ", meaning: "기초" },
            { id: '1_252', japanese: "規則", reading: "きそく", meaning: "규칙" },
            { id: '1_253', japanese: "期待", reading: "きたい", meaning: "기대" },
            { id: '1_254', japanese: "帰宅", reading: "きたく", meaning: "귀가" },
            { id: '1_255', japanese: "切手", reading: "きって", meaning: "우표" },
            { id: '1_256', japanese: "記念", reading: "きねん", meaning: "기념" },
            { id: '1_257', japanese: "基本", reading: "きほん", meaning: "기본" },
            { id: '1_258', japanese: "逆", reading: "ぎゃく", meaning: "반대, 거꾸로임" },
            { id: '1_259', japanese: "休日", reading: "きゅうじつ", meaning: "휴일" },
            { id: '1_260', japanese: "教師", reading: "きょうし", meaning: "교사" },
            { id: '1_261', japanese: "競争", reading: "きょうそう", meaning: "경쟁" },
            { id: '1_262', japanese: "共通", reading: "きょうつう", meaning: "공통" },
            { id: '1_263', japanese: "興味", reading: "きょうみ", meaning: "흥미" },
            { id: '1_264', japanese: "協力", reading: "きょうりょく", meaning: "협력" },
            { id: '1_265', japanese: "距離", reading: "きょり", meaning: "거리" },
            { id: '1_266', japanese: "記録", reading: "きろく", meaning: "기록" },
            { id: '1_267', japanese: "禁煙", reading: "きんえん", meaning: "금연" },
            { id: '1_268', japanese: "禁止", reading: "きんし", meaning: "금지" },
            { id: '1_269', japanese: "首", reading: "くび", meaning: "목" },
            { id: '1_270', japanese: "工夫", reading: "くふう", meaning: "고안, 궁리" },
            { id: '1_271', japanese: "区分", reading: "くぶん", meaning: "구분" },
            { id: '1_272', japanese: "区別", reading: "くべつ", meaning: "구별" },
            { id: '1_273', japanese: "訓練", reading: "くんれん", meaning: "훈련" },
            { id: '1_274', japanese: "経営", reading: "けいえい", meaning: "경영" },
            { id: '1_275', japanese: "計画", reading: "けいかく", meaning: "계획" },
            { id: '1_276', japanese: "経験", reading: "けいけん", meaning: "경험" },
            { id: '1_277', japanese: "経済", reading: "けいざい", meaning: "경제" },
            { id: '1_278', japanese: "計算", reading: "けいさん", meaning: "계산" },
            { id: '1_279', japanese: "経由", reading: "けいゆ", meaning: "경유" },
            { id: '1_280', japanese: "外科", reading: "げか", meaning: "외과" },
            { id: '1_281', japanese: "景色", reading: "けしき", meaning: "경치" },
            { id: '1_282', japanese: "血液", reading: "けつえき", meaning: "혈액" },
            { id: '1_283', japanese: "欠席", reading: "けっせき", meaning: "결석" },
            { id: '1_284', japanese: "欠点", reading: "けってん", meaning: "결점" },
            { id: '1_285', japanese: "煙", reading: "けむり", meaning: "연기" },
            { id: '1_286', japanese: "原因", reading: "げんいん", meaning: "원인" },
            { id: '1_287', japanese: "研究", reading: "けんきゅう", meaning: "연구" },
            { id: '1_288', japanese: "現金", reading: "げんきん", meaning: "현금" },
            { id: '1_289', japanese: "健康", reading: "けんこう", meaning: "건강" },
            { id: '1_290', japanese: "検査", reading: "けんさ", meaning: "검사" },
            { id: '1_291', japanese: "現在", reading: "げんざい", meaning: "현재" },
            { id: '1_292', japanese: "減少", reading: "げんしょう", meaning: "감소" },
            { id: '1_293', japanese: "建設", reading: "けんせつ", meaning: "건설" },
            { id: '1_294', japanese: "見物", reading: "けんぶつ", meaning: "구경" },
            { id: '1_295', japanese: "原料", reading: "げんりょう", meaning: "원료" },
            { id: '1_296', japanese: "講演", reading: "こうえん", meaning: "강연" },
            { id: '1_297', japanese: "効果", reading: "こうか", meaning: "효과" },
            { id: '1_298', japanese: "合計", reading: "ごうけい", meaning: "합계" },
            { id: '1_299', japanese: "広告", reading: "こうこく", meaning: "광고" },
            { id: '1_300', japanese: "交代", reading: "こうたい", meaning: "교대" },
            { id: '1_301', japanese: "交替", reading: "こうたい", meaning: "교체" },
            { id: '1_302', japanese: "行動", reading: "こうどう", meaning: "행동" },
            { id: '1_303', japanese: "交流", reading: "こうりゅう", meaning: "교류" },
            { id: '1_304', japanese: "氷", reading: "こおり", meaning: "얼음" },
            { id: '1_305', japanese: "呼吸", reading: "こきゅう", meaning: "호흡" },
            { id: '1_306', japanese: "腰", reading: "こし", meaning: "허리" },
            { id: '1_307', japanese: "故障", reading: "こしょう", meaning: "고장" },
            { id: '1_308', japanese: "個人", reading: "こじん", meaning: "개인" },
            { id: '1_309', japanese: "粉", reading: "こな", meaning: "가루" },
            { id: '1_310', japanese: "米", reading: "こめ", meaning: "쌀" },
            { id: '1_311', japanese: "最終", reading: "さいしゅう", meaning: "최종" },
            { id: '1_312', japanese: "最上", reading: "さいじょう", meaning: "최상" },
            { id: '1_313', japanese: "材料", reading: "ざいりょう", meaning: "재료" },
            { id: '1_314', japanese: "坂道", reading: "さかみち", meaning: "비탈길" },
            { id: '1_315', japanese: "作業", reading: "さぎょう", meaning: "작업" },
            { id: '1_316', japanese: "作物", reading: "さくもつ", meaning: "작물, 농작물" },
            { id: '1_317', japanese: "雑誌", reading: "ざっし", meaning: "잡지" },
            { id: '1_318', japanese: "左右", reading: "さゆう", meaning: "좌우" },
            { id: '1_319', japanese: "参加", reading: "さんか", meaning: "참가" },
            { id: '1_320', japanese: "賛成", reading: "さんせい", meaning: "찬성" },
            { id: '1_321', japanese: "塩", reading: "しお", meaning: "소금" },
            { id: '1_322', japanese: "支給", reading: "しきゅう", meaning: "지급" },
            { id: '1_323', japanese: "資源", reading: "しげん", meaning: "자원" },
            { id: '1_324', japanese: "支出", reading: "ししゅつ", meaning: "지출" },
            { id: '1_325', japanese: "事情", reading: "じじょう", meaning: "사정" },
            { id: '1_326', japanese: "自信", reading: "じしん", meaning: "자신" },
            { id: '1_327', japanese: "姿勢", reading: "しせい", meaning: "자세" },
            { id: '1_328', japanese: "自然", reading: "しぜん", meaning: "자연" },
            { id: '1_329', japanese: "支度", reading: "したく", meaning: "준비, 채비" },
            { id: '1_330', japanese: "失業", reading: "しつぎょう", meaning: "실업" },
            { id: '1_331', japanese: "実力", reading: "じつりょく", meaning: "실력" },
            { id: '1_332', japanese: "指導", reading: "しどう", meaning: "지도" },
            { id: '1_333', japanese: "締め切り", reading: "しめきり", meaning: "마감" },
            { id: '1_334', japanese: "地面", reading: "じめん", meaning: "지면" },
            { id: '1_335', japanese: "地元", reading: "じもと", meaning: "출신 지역, 고장, 현지" },
            { id: '1_336', japanese: "集合", reading: "しゅうごう", meaning: "집합" },
            { id: '1_337', japanese: "収集", reading: "しゅうしゅう", meaning: "수집" },
            { id: '1_338', japanese: "渋滞", reading: "じゅうたい", meaning: "정체" },
            { id: '1_339', japanese: "集中", reading: "しゅうちゅう", meaning: "집중" },
            { id: '1_340', japanese: "修理", reading: "しゅうり", meaning: "수리" },
            { id: '1_341', japanese: "縮小", reading: "しゅくしょう", meaning: "축소" },
            { id: '1_342', japanese: "手術", reading: "しゅじゅつ", meaning: "수술" },
            { id: '1_343', japanese: "手段", reading: "しゅだん", meaning: "수단" },
            { id: '1_344', japanese: "主張", reading: "しゅちょう", meaning: "주장" },
            { id: '1_345', japanese: "出張", reading: "しゅっちょう", meaning: "출장" },
            { id: '1_346', japanese: "首都", reading: "しゅと", meaning: "수도" },
            { id: '1_347', japanese: "趣味", reading: "しゅみ", meaning: "취미" },
            { id: '1_348', japanese: "順番", reading: "じゅんばん", meaning: "순번" },
            { id: '1_349', japanese: "紹介", reading: "しょうかい", meaning: "소개" },
            { id: '1_350', japanese: "商業", reading: "しょうぎょう", meaning: "상업" },
            { id: '1_351', japanese: "条件", reading: "じょうけん", meaning: "조건" },
            { id: '1_352', japanese: "乗車", reading: "じょうしゃ", meaning: "승차" },
            { id: '1_353', japanese: "招待", reading: "しょうたい", meaning: "초대" },
            { id: '1_354', japanese: "商売", reading: "しょうぱい", meaning: "장사" },
            { id: '1_355', japanese: "消費", reading: "しょうひ", meaning: "소비" },
            { id: '1_356', japanese: "商品", reading: "しょうひん", meaning: "상품" },
            { id: '1_357', japanese: "情報", reading: "じょうほう", meaning: "정보" },
            { id: '1_358', japanese: "証明", reading: "しょうめい", meaning: "증명" },
            { id: '1_359', japanese: "正面", reading: "しょうめん", meaning: "정면" },
            { id: '1_360', japanese: "植物", reading: "しょくぶつ", meaning: "식물" },
            { id: '1_361', japanese: "食器", reading: "しょっき", meaning: "식기" },
            { id: '1_362', japanese: "資料", reading: "しりょう", meaning: "자료" },
            { id: '1_363', japanese: "進行", reading: "しんこう", meaning: "진행" },
            { id: '1_364', japanese: "申請", reading: "しんせい", meaning: "신청" },
            { id: '1_365', japanese: "進歩", reading: "しんぽ", meaning: "진보" },
            { id: '1_366', japanese: "数字", reading: "すうじ", meaning: "숫자" },
            { id: '1_367', japanese: "頭痛", reading: "ずつう", meaning: "두통" },
            { id: '1_368', japanese: "砂", reading: "すな", meaning: "모래" },
            { id: '1_369', japanese: "正解", reading: "せいかい", meaning: "정답" },
            { id: '1_370', japanese: "性格", reading: "せいかく", meaning: "성격" },
            { id: '1_371', japanese: "税金", reading: "ぜいきん", meaning: "세금" },
            { id: '1_372', japanese: "制限", reading: "せいげん", meaning: "제한" },
            { id: '1_373', japanese: "成功", reading: "せいこう", meaning: "성공" },
            { id: '1_374', japanese: "正常", reading: "せいじょう", meaning: "정상" },
            { id: '1_375', japanese: "成績", reading: "せいせき", meaning: "성적" },
            { id: '1_376', japanese: "整理", reading: "せいり", meaning: "정리" },
            { id: '1_377', japanese: "石油", reading: "せきゆ", meaning: "석유" },
            { id: '1_378', japanese: "選手", reading: "せんしゅ", meaning: "선수" },
            { id: '1_379', japanese: "洗濯", reading: "せんたく", meaning: "세탁, 빨래" },
            { id: '1_380', japanese: "宣伝", reading: "せんでん", meaning: "선전" },
            { id: '1_381', japanese: "専門", reading: "せんもん", meaning: "전문" },
            { id: '1_382', japanese: "想像", reading: "そうぞう", meaning: "상상" },
            { id: '1_383', japanese: "早退", reading: "そうたい", meaning: "조퇴" },
            { id: '1_384', japanese: "相談", reading: "そうだん", meaning: "상담" },
            { id: '1_385', japanese: "速度", reading: "そくど", meaning: "속도" },
            { id: '1_386', japanese: "底", reading: "そこ", meaning: "바닥" },
            { id: '1_387', japanese: "卒業", reading: "そつぎょう", meaning: "졸업" },
            { id: '1_388', japanese: "存在", reading: "そんざい", meaning: "존재" },
            { id: '1_389', japanese: "大会", reading: "たいかい", meaning: "대회" },
            { id: '1_390', japanese: "代金", reading: "だいきん", meaning: "대금" },
            { id: '1_391', japanese: "滞在", reading: "たいざい", meaning: "체재" },
            { id: '1_392', japanese: "台所", reading: "だいどころ", meaning: "부엌" },
            { id: '1_393', japanese: "台風", reading: "たいふう", meaning: "태풍" },
            { id: '1_394', japanese: "体力", reading: "たいりょく", meaning: "체력" },
            { id: '1_395', japanese: "他人", reading: "たにん", meaning: "타인" },
            { id: '1_396', japanese: "誕生", reading: "たんじょう", meaning: "탄생" },
            { id: '1_397', japanese: "団体", reading: "だんたい", meaning: "단체" },
            { id: '1_398', japanese: "遅刻", reading: "ちこく", meaning: "지각" },
            { id: '1_399', japanese: "中古", reading: "ちゅうこ", meaning: "중고" },
            { id: '1_400', japanese: "駐車", reading: "ちゅうしゃ", meaning: "주차" },
            { id: '1_401', japanese: "調子", reading: "ちょうし", meaning: "(몸, 기계) 상태" },
            { id: '1_402', japanese: "朝食", reading: "ちょうしょく", meaning: "조식" },
            { id: '1_403', japanese: "貯金", reading: "ちょきん", meaning: "저금" },
            { id: '1_404', japanese: "直接", reading: "ちょくせつ", meaning: "직접" },
            { id: '1_405', japanese: "通勤", reading: "つうきん", meaning: "통근" },
            { id: '1_406', japanese: "通訳", reading: "つうやく", meaning: "통역" },
            { id: '1_407', japanese: "都合", reading: "つごう", meaning: "사정, 형편" },
            { id: '1_408', japanese: "停電", reading: "ていでん", meaning: "정전" },
            { id: '1_409', japanese: "伝言", reading: "でんごん", meaning: "전언, 전하는 말, 메시지" },
            { id: '1_410', japanese: "天井", reading: "てんじょう", meaning: "천정" },
            { id: '1_411', japanese: "動作", reading: "どうさ", meaning: "동작" },
            { id: '1_412', japanese: "当日", reading: "とうじつ", meaning: "당일" },
            { id: '1_413', japanese: "登場", reading: "とうじょう", meaning: "등장" },
            { id: '1_414', japanese: "到着", reading: "とうちゃく", meaning: "도착" },
            { id: '1_415', japanese: "登録", reading: "とうろく", meaning: "등록" },
            { id: '1_416', japanese: "独身", reading: "どくしん", meaning: "독신" },
            { id: '1_417', japanese: "特徴", reading: "とくちょう", meaning: "특징" },
            { id: '1_418', japanese: "独立", reading: "どくりつ", meaning: "독립" },
            { id: '1_419', japanese: "登山", reading: "とざん", meaning: "등산" },
            { id: '1_420', japanese: "途中", reading: "とちゅう", meaning: "도중" },
            { id: '1_421', japanese: "努力", reading: "どりょく", meaning: "노력" },
            { id: '1_422', japanese: "内緒", reading: "ないしょ", meaning: "비밀" },
            { id: '1_423', japanese: "内容", reading: "ないよう", meaning: "내용" },
            { id: '1_424', japanese: "中身", reading: "なかみ", meaning: "속, 알맹이, 내용물" },
            { id: '1_425', japanese: "波", reading: "なみ", meaning: "파도" },
            { id: '1_426', japanese: "涙", reading: "なみだ", meaning: "눈물" },
            { id: '1_427', japanese: "荷物", reading: "にもつ", meaning: "짐" },
            { id: '1_428', japanese: "人間", reading: "にんげん", meaning: "인간" },
            { id: '1_429', japanese: "値段", reading: "ねだん", meaning: "가격" },
            { id: '1_430', japanese: "根", reading: "ね", meaning: "뿌리" },
            { id: '1_431', japanese: "年中", reading: "ねんじゅう", meaning: "연중" },
            { id: '1_432', japanese: "農業", reading: "のうぎょう", meaning: "농업" },
            { id: '1_433', japanese: "歯", reading: "は", meaning: "이, 치아" },
            { id: '1_434', japanese: "葉", reading: "は", meaning: "잎" },
            { id: '1_435', japanese: "~倍", reading: "~ばい", meaning: "~배" },
            { id: '1_436', japanese: "発生", reading: "はっせい", meaning: "발생" },
            { id: '1_437', japanese: "発展", reading: "はってん", meaning: "발전" },
            { id: '1_438', japanese: "発表", reading: "はっぴょう", meaning: "발표" },
            { id: '1_439', japanese: "反対", reading: "はんたい", meaning: "반대" },
            { id: '1_440', japanese: "販売", reading: "はんばい", meaning: "판매" },
            { id: '1_441', japanese: "比較", reading: "ひかく", meaning: "비교" },
            { id: '1_442', japanese: "光", reading: "ひかり", meaning: "빛" },
            { id: '1_443', japanese: "否定", reading: "ひてい", meaning: "부정" },
            { id: '1_444', japanese: "表示", reading: "ひょうじ", meaning: "표시" },
            { id: '1_445', japanese: "表面", reading: "ひょうめん", meaning: "표면" },
            { id: '1_446', japanese: "風景", reading: "ふうけい", meaning: "풍경" },
            { id: '1_447', japanese: "複数", reading: "ふくすう", meaning: "복수" },
            { id: '1_448', japanese: "袋", reading: "ふくろ", meaning: "주머니, 봉지" },
            { id: '1_449', japanese: "物価", reading: "ぶっか", meaning: "물가" },
            { id: '1_450', japanese: "沸騰", reading: "ふっとう", meaning: "비등, 물이 끓음" },
            { id: '1_451', japanese: "布団", reading: "ふとん", meaning: "이불" },
            { id: '1_452', japanese: "部分", reading: "ぶぶん", meaning: "부분" },
            { id: '1_453', japanese: "文章", reading: "ぶんしょう", meaning: "문장" },
            { id: '1_454', japanese: "分類", reading: "ぶんるい", meaning: "분류" },
            { id: '1_455', japanese: "平均", reading: "へいきん", meaning: "평균" },
            { id: '1_456', japanese: "変化", reading: "へんか", meaning: "변화" },
            { id: '1_457', japanese: "貿易", reading: "ぼうえき", meaning: "무역" },
            { id: '1_458', japanese: "方向", reading: "ほうこう", meaning: "방향" },
            { id: '1_459', japanese: "方法", reading: "ほうほう", meaning: "방법" },
            { id: '1_460', japanese: "訪問", reading: "ほうもん", meaning: "방문" },
            { id: '1_461', japanese: "法律", reading: "ほうりつ", meaning: "법률" },
            { id: '1_462', japanese: "募集", reading: "ぼしゅう", meaning: "모집" },
            { id: '1_463', japanese: "孫", reading: "まご", meaning: "손자" },
            { id: '1_464', japanese: "豆", reading: "まめ", meaning: "콩" },
            { id: '1_465', japanese: "満足", reading: "まんぞく", meaning: "만족" },
            { id: '1_466', japanese: "湖", reading: "みずうみ", meaning: "호수" },
            { id: '1_467', japanese: "緑", reading: "みどり", meaning: "녹색, 초록" },
            { id: '1_468', japanese: "未来", reading: "みらい", meaning: "미래" },
            { id: '1_469', japanese: "命令", reading: "めいれい", meaning: "명령" },
            { id: '1_470', japanese: "免許", reading: "めんきょ", meaning: "면허" },
            { id: '1_471', japanese: "面接", reading: "めんせつ", meaning: "면접" },
            { id: '1_472', japanese: "目的", reading: "もくてき", meaning: "목적" },
            { id: '1_473', japanese: "目標", reading: "もくひょう", meaning: "목표" },
            { id: '1_474', japanese: "文字", reading: "もじ", meaning: "문자" },
            { id: '1_475', japanese: "森", reading: "もり", meaning: "숲" },
            { id: '1_476', japanese: "文句", reading: "もんく", meaning: "불평, 불만" },
            { id: '1_477', japanese: "屋根", reading: "やね", meaning: "지붕" },
            { id: '1_478', japanese: "床", reading: "ゆか", meaning: "마루" },
            { id: '1_479', japanese: "輸出", reading: "ゆしゅつ", meaning: "수출" },
            { id: '1_480', japanese: "輸入", reading: "ゆにゅう", meaning: "수입" },
            { id: '1_481', japanese: "容器", reading: "ようき", meaning: "용기" },
            { id: '1_482', japanese: "横", reading: "よこ", meaning: "옆" },
            { id: '1_483', japanese: "汚れ", reading: "よごれ", meaning: "더러움, 오염" },
            { id: '1_484', japanese: "予測", reading: "よそく", meaning: "예측" },
            { id: '1_485', japanese: "夜中", reading: "よなか", meaning: "밤중" },
            { id: '1_486', japanese: "予防", reading: "よぼう", meaning: "예방" },
            { id: '1_487', japanese: "留守", reading: "るす", meaning: "부재(중)" },
            { id: '1_488', japanese: "列", reading: "れつ", meaning: "열, 줄" },
            { id: '1_489', japanese: "連休", reading: "れんきゅう", meaning: "연휴" },
            { id: '1_490', japanese: "訳", reading: "わけ", meaning: "이유" },
            { id: '1_491', japanese: "割合", reading: "わりあい", meaning: "비율" },
            { id: '1_492', japanese: "相変わらず", reading: "あいかわらず", meaning: "변함없이" },
            { id: '1_493', japanese: "必ず", reading: "かならず", meaning: "반드시" },
            { id: '1_494', japanese: "急に", reading: "きゅうに", meaning: "갑자기" },
            { id: '1_495', japanese: "次第に", reading: "しだいに", meaning: "점점, 서서히" },
            { id: '1_496', japanese: "全て", reading: "すべて", meaning: "모두" },
            { id: '1_497', japanese: "絶対", reading: "ぜったい", meaning: "절대로, 꼭" },
            { id: '1_498', japanese: "多少", reading: "たしょう", meaning: "다소" },
            { id: '1_499', japanese: "当然", reading: "とうぜん", meaning: "당연히" },
            { id: '1_500', japanese: "突然", reading: "とつぜん", meaning: "돌연, 갑자기" },
            ]
    },
    // { name: '다른 단어장', words: [...] } // -> 다른 단어장 추가 위치
];

// 모든 단어장의 단어를 하나의 배열로 합칩니다. (즐겨찾기, 검색 등에 사용)
const allVocabulary = vocabularySets.flatMap(set => set.words);
