registerVocabularySet({
    name: '수제 일본어단어장',
    words: [
        { id: 'handmade_1', japanese: "出来る", reading: "できる", meaning: "할 수 있다", type: 'verb', difficulty: 15, verb_info: '2자' },
        { id: 'handmade_2', japanese: "助ける", reading: "たすける", meaning: "돕다", type: 'verb', difficulty: 22, verb_info: '2타' },
        { id: 'handmade_3', japanese: "偉そうにする", reading: "えらそうにする", meaning: "잘난 체 하다", type: 'verb', difficulty: 38 },
        { id: 'handmade_4', japanese: "痺れる", reading: "しびれる", meaning: "저리다", type: 'verb', difficulty: 35, verb_info: '2자' },
        { id: 'handmade_5', japanese: "昔", reading: "むかし", meaning: "옛날", type: 'noun', difficulty: 25 },
        { id: 'handmade_6', japanese: "渇く", reading: "かわく", meaning: "목마르다", type: 'verb', difficulty: 28, verb_info: '1자' },
        { id: 'handmade_7', japanese: "生まれる・産まれる", reading: "うまれる", meaning: "태어나다", type: 'verb', difficulty: 20, verb_info: '2자' },
        { id: 'handmade_8', japanese: "宝物", reading: "たからもの", meaning: "보물", type: 'noun', difficulty: 28 },
        { id: 'handmade_9', japanese: "蘞い", reading: "えぐい", meaning: "칼칼하다, 끔찍하다, 쩐다", type: 'i_adj', difficulty: 55 },
        { id: 'handmade_10', japanese: "貴様", reading: "きさま", meaning: "네 녀석", type: 'noun', difficulty: 45 },
        { id: 'handmade_11', japanese: "底知れない", reading: "そこしれない", meaning: "정체 모를, 끝을 모르는", type: 'i_adj', difficulty: 50 },
        { id: 'handmade_12', japanese: "豆知識", reading: "まめちしき", meaning: "토막 지식", type: 'noun', difficulty: 40 },
        { id: 'handmade_13', japanese: "様子", reading: "ようす", meaning: "상태, 모습", type: 'noun', difficulty: 28 },
        { id: 'handmade_14', japanese: "泥", reading: "どろ", meaning: "진흙", type: 'noun', difficulty: 35 },
        { id: 'handmade_15', japanese: "掃除", reading: "そうじ", meaning: "청소", type: 'noun', difficulty: 18 },
        { id: 'handmade_16', japanese: "戻す", reading: "もどす", meaning: "되돌리다", type: 'verb', difficulty: 24, verb_info: '1타' },
        { id: 'handmade_17', japanese: "丁寧に", reading: "ていねいに", meaning: "정중히, 정성껏", type: 'adv', difficulty: 25 },
        { id: 'handmade_18', japanese: "隙間", reading: "すきま", meaning: "틈, 틈새", type: 'noun', difficulty: 35 },
        { id: 'handmade_19', japanese: "差し込む", reading: "さしこむ", meaning: "(빛이) 비치다", type: 'verb', difficulty: 35, verb_info: '1자' },
        { id: 'handmade_20', japanese: "諦める", reading: "あきらめる", meaning: "포기하다", type: 'verb', difficulty: 30, verb_info: '2타' },
        { id: 'handmade_21', japanese: "謎", reading: "なぞ", meaning: "수수께끼, 불가사의", type: 'noun', difficulty: 28 },
        { id: 'handmade_22', japanese: "店", reading: "みせ", meaning: "가게", type: 'noun', difficulty: 12 },
        { id: 'handmade_23', japanese: "髭", reading: "ひげ", meaning: "수염", type: 'noun', difficulty: 35 },
        { id: 'handmade_24', japanese: "髪", reading: "かみ", meaning: "머리카락", type: 'noun', difficulty: 20 },
        { id: 'handmade_25', japanese: "船", reading: "ふね", meaning: "배", type: 'noun', difficulty: 20 },
        { id: 'handmade_26', japanese: "嵐", reading: "あらし", meaning: "폭풍", type: 'noun', difficulty: 30 },
        { id: 'handmade_27', japanese: "東", reading: "ひがし", meaning: "동쪽", type: 'noun', difficulty: 15 },
        { id: 'handmade_28', japanese: "西", reading: "にし", meaning: "서쪽", type: 'noun', difficulty: 15 },
        { id: 'handmade_29', japanese: "南", reading: "みなみ", meaning: "남쪽", type: 'noun', difficulty: 15 },
        { id: 'handmade_30', japanese: "北", reading: "きた", meaning: "북쪽", type: 'noun', difficulty: 15 },
        { id: 'handmade_31', japanese: "外", reading: "そと", meaning: "밖", type: 'noun', difficulty: 15 },
        { id: 'handmade_32', japanese: "今朝", reading: "けさ", meaning: "오늘 아침", type: 'noun', difficulty: 18 },
        { id: 'handmade_33', japanese: "暑い", reading: "あつい", meaning: "덥다", type: 'i_adj', difficulty: 15 },
        { id: 'handmade_34', japanese: "箱", reading: "ばこ", meaning: "상자, 함", type: 'noun', difficulty: 20 },
        { id: 'handmade_35', japanese: "瞳", reading: "ひとみ", meaning: "눈동자", type: 'noun', difficulty: 35 },
        { id: 'handmade_36', japanese: "試験", reading: "しけん", meaning: "시험", type: 'noun', difficulty: 22 },
        { id: 'handmade_37', japanese: "取り込む", reading: "とりこむ", meaning: "거두어 들이다", type: 'verb', difficulty: 38, verb_info: '1타' },
        { id: 'handmade_38', japanese: "蛇口", reading: "じゃぐち", meaning: "수도꼭지", type: 'noun', difficulty: 38 },
        { id: 'handmade_39', japanese: "問題", reading: "もんだい", meaning: "문제", type: 'noun', difficulty: 18 },
        { id: 'handmade_40', japanese: "消防", reading: "しょうぼう", meaning: "소방", type: 'noun', difficulty: 32 },
        { id: 'handmade_41', japanese: "駅", reading: "えき", meaning: "(기차 등) 역", type: 'noun', difficulty: 10 },
        { id: 'handmade_42', japanese: "ご飯", reading: "ごはん", meaning: "밥, 식사", type: 'noun', difficulty: 12 },
        { id: 'handmade_43', japanese: "酒", reading: "さけ", meaning: "술", type: 'noun', difficulty: 18 },
        { id: 'handmade_44', japanese: "授業", reading: "じゅぎょう", meaning: "수업", type: 'noun', difficulty: 22 },
        { id: 'handmade_45', japanese: "新聞", reading: "しんぶん", meaning: "신문", type: 'noun', difficulty: 20 },
        { id: 'handmade_46', japanese: "住所", reading: "じゅうしょ", meaning: "주소", type: 'noun', difficulty: 22 },
        { id: 'handmade_47', japanese: "電話", reading: "でんわ", meaning: "전화", type: 'noun', difficulty: 15 },
        { id: 'handmade_48', japanese: "番号", reading: "ばんご", meaning: "번호", type: 'noun', difficulty: 18 },
        { id: 'handmade_49', japanese: "描く", reading: "かく・えがく", meaning: "그리다", type: 'verb', difficulty: 28, verb_info: '1타' },
        { id: 'handmade_50', japanese: "勉強", reading: "べんきょう", meaning: "공부", type: 'noun', difficulty: 15 },
        { id: 'handmade_51', japanese: "変だ", reading: "へんだ", meaning: "이상하다", type: 'na_adj', difficulty: 22 },
        { id: 'handmade_52', japanese: "味", reading: "あじ", meaning: "맛", type: 'noun', difficulty: 20 },
        { id: 'handmade_53', japanese: "赤ちゃん", reading: "あかちゃん", meaning: "아기", type: 'noun', difficulty: 20 },
        { id: 'handmade_54', japanese: "失敗", reading: "しっぱい", meaning: "실패", type: 'noun', difficulty: 25 },
        { id: 'handmade_55', japanese: "写真", reading: "しゃしん", meaning: "사진", type: 'noun', difficulty: 18 },
        { id: 'handmade_56', japanese: "収める", reading: "おさめる", meaning: "담다, 얻다", type: 'verb', difficulty: 38, verb_info: '2타' },
        { id: 'handmade_57', japanese: "揚げる", reading: "あげる", meaning: "튀기다", type: 'verb', difficulty: 32, verb_info: '2타' },
        { id: 'handmade_58', japanese: "揚げ物", reading: "あげもの", meaning: "튀김", type: 'noun', difficulty: 30 },
        { id: 'handmade_59', japanese: "車", reading: "くるま", meaning: "자동차", type: 'noun', difficulty: 12 },
        { id: 'handmade_60', japanese: "渡す", reading: "わたす", meaning: "건너다", type: 'verb', difficulty: 22, verb_info: '1타' },
        { id: 'handmade_61', japanese: "水槽", reading: "すいそう", meaning: "수조", type: 'noun', difficulty: 45 },
        { id: 'handmade_62', japanese: "選手", reading: "せんしゅ", meaning: "선수", type: 'noun', difficulty: 25 },
        { id: 'handmade_63', japanese: "決める", reading: "きめる", meaning: "결정하다", type: 'verb', difficulty: 22, verb_info: '2타' },
        { id: 'handmade_64', japanese: "机", reading: "つくえ", meaning: "책상", type: 'noun', difficulty: 15 },
        { id: 'handmade_65', japanese: "縁", reading: "へり", meaning: "모서리", type: 'noun', difficulty: 50 },
        { id: 'handmade_66', japanese: "気絶", reading: "きぜつ", meaning: "기절", type: 'noun', difficulty: 45 },
        { id: 'handmade_67', japanese: "針", reading: "はり", meaning: "(벌, 시계 등의) 침", type: 'noun', difficulty: 30 },
        { id: 'handmade_68', japanese: "鍼", reading: "はり", meaning: "(의료용) 침", type: 'noun', difficulty: 60 },
        { id: 'handmade_69', japanese: "腰", reading: "こし", meaning: "허리", type: 'noun', difficulty: 25 },
        { id: 'handmade_70', japanese: "和らぐ", reading: "やわらぐ", meaning: "누그러지다", type: 'verb', difficulty: 40, verb_info: '1자' },
        { id: 'handmade_71', japanese: "話", reading: "はなし", meaning: "이야기", type: 'noun', difficulty: 12 },
        { id: 'handmade_72', japanese: "昨日", reading: "きのう", meaning: "어제", type: 'noun', difficulty: 15 },
        { id: 'handmade_73', japanese: "碁", reading: "ご", meaning: "바둑", type: 'noun', difficulty: 40 },
        { id: 'handmade_74', japanese: "結果", reading: "けっか", meaning: "결과", type: 'noun', difficulty: 25 },
        { id: 'handmade_75', japanese: "一生懸命", reading: "いっしょうけんめい", meaning: "열심히", type: 'adv', difficulty: 28 },
        { id: 'handmade_76', japanese: "将来", reading: "しょうらい", meaning: "장래", type: 'noun', difficulty: 25 },
        { id: 'handmade_77', japanese: "動物", reading: "どうぶつ", meaning: "동물", type: 'noun', difficulty: 20 },
        { id: 'handmade_78', japanese: "進路", reading: "しんろ", meaning: "진로", type: 'noun', difficulty: 30 },
        { id: 'handmade_79', japanese: "合格", reading: "ごうかく", meaning: "합격", type: 'noun', difficulty: 25 },
        { id: 'handmade_80', japanese: "耳", reading: "みみ", meaning: "귀", type: 'noun', difficulty: 15 },
        { id: 'handmade_81', japanese: "引っ越す", reading: "ひっこす", meaning: "이사하다", type: 'verb', difficulty: 28, verb_info: '1자' },
        { id: 'handmade_82', japanese: "連絡", reading: "れんらく", meaning: "연락", type: 'noun', difficulty: 22 },
        { id: 'handmade_83', japanese: "先祖", reading: "せんぞ", meaning: "선조", type: 'noun', difficulty: 35 },
        { id: 'handmade_84', japanese: "流浪", reading: "るろう", meaning: "유랑", type: 'noun', difficulty: 65 },
        { id: 'handmade_85', japanese: "末", reading: "すえ", meaning: "끝", type: 'noun', difficulty: 30 },
        { id: 'handmade_86', japanese: "自分", reading: "じぶん", meaning: "자신", type: 'noun', difficulty: 18 },
        { id: 'handmade_87', japanese: "大切だ", reading: "たいせつだ", meaning: "중요함, 소중함", type: 'na_adj', difficulty: 22 },
        { id: 'handmade_88', japanese: "頭", reading: "あたま", meaning: "머리", type: 'noun', difficulty: 15 },
        { id: 'handmade_89', japanese: "痛み止め", reading: "いたみどめ", meaning: "진통제", type: 'noun', difficulty: 35 },
        { id: 'handmade_90', japanese: "果物", reading: "くだもの", meaning: "과일", type: 'noun', difficulty: 20 },
        { id: 'handmade_91', japanese: "修理", reading: "しゅうり", meaning: "수리", type: 'noun', difficulty: 25 },
        { id: 'handmade_92', japanese: "屋根", reading: "やね", meaning: "지붕", type: 'noun', difficulty: 25 },
        { id: 'handmade_93', japanese: "肌", reading: "はだ", meaning: "피부", type: 'noun', difficulty: 25 },
        { id: 'handmade_94', japanese: "寒い", reading: "さむい", meaning: "춥다", type: 'i_adj', difficulty: 15 },
        { id: 'handmade_95', japanese: "厳しい", reading: "きびしい", meaning: "가혹하다, 심하다", type: 'i_adj', difficulty: 28 },
        { id: 'handmade_96', japanese: "冷たい", reading: "つめたい", meaning: "차갑다", type: 'i_adj', difficulty: 18 },
        { id: 'handmade_97', japanese: "歯", reading: "は", meaning: "치아", type: 'noun', difficulty: 15 },
        { id: 'handmade_98', japanese: "汗", reading: "あせ", meaning: "땀", type: 'noun', difficulty: 22 },
        { id: 'handmade_99', japanese: "脱ぐ", reading: "ぬぐ", meaning: "벗다", type: 'verb', difficulty: 24, verb_info: '1타' },
        { id: 'handmade_100', japanese: "誰", reading: "だれ", meaning: "누구", type: 'noun', difficulty: 12 },
        { id: 'handmade_101', japanese: "事件", reading: "じけん", meaning: "사건", type: 'noun', difficulty: 25 },
        { id: 'handmade_102', japanese: "一部始終", reading: "いちぶしじゅう", meaning: "자초지종", type: 'noun', difficulty: 55 },
        { id: 'handmade_103', japanese: "本心", reading: "ほんしん", meaning: "본심", type: 'noun', difficulty: 32 },
        { id: 'handmade_104', japanese: "会議", reading: "かいぎ", meaning: "기회", type: 'noun', difficulty: 25 },
        { id: 'handmade_105', japanese: "意見", reading: "いけん", meaning: "의견", type: 'noun', difficulty: 25 },
        { id: 'handmade_106', japanese: "きちんと", reading: "きちんと", meaning: "확실히", type: 'adv', difficulty: 28 },
        { id: 'handmade_107', japanese: "著者", reading: "ちょしゃ", meaning: "저자", type: 'noun', difficulty: 32 },
        { id: 'handmade_108', japanese: "違う", reading: "ちがう", meaning: "다르다, 틀리다", type: 'verb', difficulty: 18, verb_info: '1자' },
        { id: 'handmade_109', japanese: "世界観", reading: "せかいかん", meaning: "세계관", type: 'noun', difficulty: 35 },
        { id: 'handmade_110', japanese: "耳元", reading: "みみもと", meaning: "귓가", type: 'noun', difficulty: 32 },
        { id: 'handmade_111', japanese: "緊張", reading: "きんちょう", meaning: "긴장", type: 'noun', difficulty: 28 },
        { id: 'handmade_112', japanese: "愛称", reading: "あいしょう", meaning: "애칭", type: 'noun', difficulty: 45 },
        { id: 'handmade_113', japanese: "遠い", reading: "とおい", meaning: "멀다", type: 'i_adj', difficulty: 18 },
        { id: 'handmade_114', japanese: "遠く", reading: "とおく", meaning: "먼 곳", type: 'noun', difficulty: 20 },
        { id: 'handmade_115', japanese: "傾ける", reading: "かたむける", meaning: "(물건, 노력, 운세 등을) 기울이다, 기울게 하다", type: 'verb', difficulty: 35, verb_info: '2타' },
        { id: 'handmade_116', japanese: "使う", reading: "つかう", meaning: "사용하다", type: 'verb', difficulty: 12, verb_info: '1타' },
        { id: 'handmade_117', japanese: "黒板", reading: "こくばん", meaning: "칠판", type: 'noun', difficulty: 25 },
        { id: 'handmade_118', japanese: "入る", reading: "はいる", meaning: "들어가다", type: 'verb', difficulty: 12, verb_info: '1자' },
        { id: 'handmade_119', japanese: "帰る", reading: "かえる", meaning: "돌아가다", type: 'verb', difficulty: 12, verb_info: '1자' },
        { id: 'handmade_120', japanese: "部屋", reading: "へや", meaning: "방", type: 'noun', difficulty: 15 },
        { id: 'handmade_121', japanese: "窓", reading: "まど", meaning: "창문", type: 'noun', difficulty: 15 },
        { id: 'handmade_122', japanese: "曜日", reading: "ようび", meaning: "요일", type: 'noun', difficulty: 18 },
        { id: 'handmade_123', japanese: "銀行", reading: "ぎんこう", meaning: "은행", type: 'noun', difficulty: 20 },
        { id: 'handmade_124', japanese: "去年", reading: "きょねん", meaning: "작년", type: 'noun', difficulty: 20 },
        { id: 'handmade_125', japanese: "学位", reading: "がくい", meaning: "학위", type: 'noun', difficulty: 45 },
        { id: 'handmade_126', japanese: "後ろ", reading: "うしろ", meaning: "뒤", type: 'noun', difficulty: 15 },
        { id: 'handmade_127', japanese: "金額", reading: "きんがく", meaning: "금액", type: 'noun', difficulty: 28 },
        { id: 'handmade_128', japanese: "紐", reading: "ひも", meaning: "끈", type: 'noun', difficulty: 30 },
        { id: 'handmade_129', japanese: "泥棒", reading: "どろぼう", meaning: "도둑", type: 'noun', difficulty: 32 },
        { id: 'handmade_130', japanese: "警察", reading: "けいさつ", meaning: "경찰", type: 'noun', difficulty: 25 },
        { id: 'handmade_131', japanese: "紙", reading: "かみ", meaning: "종이", type: 'noun', difficulty: 15 },
        { id: 'handmade_132', japanese: "説明", reading: "せつめい", meaning: "설명", type: 'noun', difficulty: 22 },
        { id: 'handmade_133', japanese: "腕", reading: "うで", meaning: "팔", type: 'noun', difficulty: 22 },
        { id: 'handmade_134', japanese: "逃す", reading: "のがす", meaning: "놓치다", type: 'verb', difficulty: 35, verb_info: '1타' },
        { id: 'handmade_135', japanese: "手がかり", reading: "てがかり", meaning: "실마리", type: 'noun', difficulty: 38 },
        { id: 'handmade_136', japanese: "政治家", reading: "せいじか", meaning: "정치가", type: 'noun', difficulty: 32 },
        { id: 'handmade_137', japanese: "絶大だ", reading: "ぜつだいだ", meaning: "지대하다", type: 'na_adj', difficulty: 48 },
        { id: 'handmade_138', japanese: "権力", reading: "けんりょく", meaning: "권력", type: 'noun', difficulty: 38 },
        { id: 'handmade_139', japanese: "社長", reading: "しゃちょう", meaning: "사장", type: 'noun', difficulty: 25 },
        { id: 'handmade_140', japanese: "道路", reading: "どうろ", meaning: "도로", type: 'noun', difficulty: 22 },
        { id: 'handmade_141', japanese: "東京", reading: "とうきょう", meaning: "도쿄", type: 'noun', difficulty: 15 },
        { id: 'handmade_142', japanese: "大阪", reading: "おおさか", meaning: "오사카", type: 'noun', difficulty: 15 },
        { id: 'handmade_143', japanese: "軽い", reading: "かるい", meaning: "가볍다", type: 'i_adj', difficulty: 18 },
        { id: 'handmade_144', japanese: "声", reading: "こえ", meaning: "목소리", type: 'noun', difficulty: 18 },
        { id: 'handmade_145', japanese: "腐敗", reading: "ふはい", meaning: "부패", type: 'noun', difficulty: 50 },
        { id: 'handmade_146', japanese: "食卓", reading: "しょくたく", meaning: "식탁", type: 'noun', difficulty: 35 },
        { id: 'handmade_147', japanese: "ハエ", reading: "はえ", meaning: "파리", type: 'noun', difficulty: 30 },
        { id: 'handmade_148', japanese: "壁", reading: "かべ", meaning: "벽", type: 'noun', difficulty: 20 },
        { id: 'handmade_149', japanese: "刺す", reading: "さす", meaning: "찌르다, 꿰다, (벌레에) 쏘이다", type: 'verb', difficulty: 30, verb_info: '1타' },
        { id: 'handmade_150', japanese: "洋服", reading: "ようふく", meaning: "양복", type: 'noun', difficulty: 25 },
        { id: 'handmade_151', japanese: "宿題", reading: "しゅくだい", meaning: "숙제", type: 'noun', difficulty: 18 },
        { id: 'handmade_152', japanese: "妻", reading: "つま", meaning: "아내", type: 'noun', difficulty: 22 },
        { id: 'handmade_153', japanese: "料理", reading: "りょうり", meaning: "요리", type: 'noun', difficulty: 22 },
        { id: 'handmade_154', japanese: "辞書", reading: "じしょ", meaning: "사전", type: 'noun', difficulty: 20 }
    ]
});
