registerVocabularySet({
    name: '다락원 알짜 일본어 VOCA 동사',
    words: [
        { id: 'darakwonverb_1', japanese: "寝る", reading: "ねる", meaning: "자다, 눕다", type: 'verb', difficulty: 12, verb_info: '2자' },
        { id: 'darakwonverb_2', japanese: "寝かす", reading: "ねかす", meaning: "(잠을) 재우다, 누이다", type: 'verb', difficulty: 32, verb_info: '1타' },
        { id: 'darakwonverb_3', japanese: "眠る", reading: "ねむる", meaning: "잠들다", type: 'verb', difficulty: 22, verb_info: '1자' },
        { id: 'darakwonverb_4', japanese: "覚める", reading: "さめる", meaning: "깨다", type: 'verb', difficulty: 28, verb_info: '2자' },
        { id: 'darakwonverb_5', japanese: "起きる", reading: "おきる", meaning: "일어나다", type: 'verb', difficulty: 12, verb_info: '2자' },
        { id: 'darakwonverb_6', japanese: "起こす", reading: "おこす", meaning: "(잠을) 깨우다, (쓰러진 것을) 일으키다", type: 'verb', difficulty: 18, verb_info: '1타' },
        { id: 'darakwonverb_7', japanese: "畳む", reading: "たたむ", meaning: "(이불 등을) 개다, (우산을) 접다, 걷어치우다", type: 'verb', difficulty: 34, verb_info: '1타' },
        { id: 'darakwonverb_8', japanese: "洗う", reading: "あらう", meaning: "씻다, (머리를) 감다, (빨래를) 빨다", type: 'verb', difficulty: 15, verb_info: '1타' },
        { id: 'darakwonverb_9', japanese: "剃る", reading: "そる", meaning: "깎다, 면도하다", type: 'verb', difficulty: 38, verb_info: '1타' },
        { id: 'darakwonverb_10', japanese: "磨く", reading: "みがく", meaning: "닦다", type: 'verb', difficulty: 22, verb_info: '1타' },
        { id: 'darakwonverb_11', japanese: "拭く", reading: "ふく", meaning: "닦다", type: 'verb', difficulty: 24, verb_info: '1타' },
        { id: 'darakwonverb_12', japanese: "休む", reading: "やすむ", meaning: "쉬다, 결석하다, 취침하다", type: 'verb', difficulty: 12, verb_info: '1자' },
        { id: 'darakwonverb_13', japanese: "明ける", reading: "あける", meaning: "(날이) 밝다, (해가) 바뀌다", type: 'verb', difficulty: 28, verb_info: '2자' },
        { id: 'darakwonverb_14', japanese: "暮れる", reading: "くれる", meaning: "저물다, 지새우다", type: 'verb', difficulty: 28, verb_info: '2자' },
        { id: 'darakwonverb_15', japanese: "沈む", reading: "しずむ", meaning: "가라앉다, (해/달이) 지다", type: 'verb', difficulty: 35, verb_info: '1자' },
        { id: 'darakwonverb_16', japanese: "吹く", reading: "ふく", meaning: "(바람이) 불다, (입으로/악기를) 불다, 허풍 떨다", type: 'verb', difficulty: 22, verb_info: '1자' },
        { id: 'darakwonverb_17', japanese: "降る", reading: "ふる", meaning: "(비 등이) 내리다", type: 'verb', difficulty: 15, verb_info: '1자' },
        { id: 'darakwonverb_18', japanese: "止む", reading: "やむ", meaning: "그치다, 멎다", type: 'verb', difficulty: 26, verb_info: '1자' },
        { id: 'darakwonverb_19', japanese: "凍る", reading: "こおる", meaning: "얼다", type: 'verb', difficulty: 30, verb_info: '1자' },
        { id: 'darakwonverb_20', japanese: "溶ける", reading: "とける", meaning: "녹다", type: 'verb', difficulty: 34, verb_info: '2자' },
        { id: 'darakwonverb_21', japanese: "光る", reading: "ひかる", meaning: "빛나다", type: 'verb', difficulty: 24, verb_info: '1자' },
        { id: 'darakwonverb_22', japanese: "輝く", reading: "かがやく", meaning: "빛나다", type: 'verb', difficulty: 35, verb_info: '1자' },
        { id: 'darakwonverb_23', japanese: "晴れる", reading: "はれる", meaning: "맑게 개다, 마음이 밝아지다", type: 'verb', difficulty: 18, verb_info: '2자' },
        { id: 'darakwonverb_24', japanese: "曇る", reading: "くもる", meaning: "(날씨가) 흐려지다, 희미해지다", type: 'verb', difficulty: 18, verb_info: '1자' },
        { id: 'darakwonverb_25', japanese: "漏れる", reading: "もれる", meaning: "(물/빛/비밀 등이) 새다", type: 'verb', difficulty: 36, verb_info: '2자' },
        { id: 'darakwonverb_26', japanese: "鳴る", reading: "なる", meaning: "울리다", type: 'verb', difficulty: 22, verb_info: '1자' },
        { id: 'darakwonverb_27', japanese: "続ける", reading: "つづける", meaning: "계속하다", type: 'verb', difficulty: 24, verb_info: '2타' },
        { id: 'darakwonverb_28', japanese: "遭う", reading: "あう", meaning: "(일을) 당하다, 겪다", type: 'verb', difficulty: 38, verb_info: '1자' },
        { id: 'darakwonverb_29', japanese: "喜ぶ", reading: "よろこぶ", meaning: "기뻐하다", type: 'verb', difficulty: 26, verb_info: '1자' },
        { id: 'darakwonverb_30', japanese: "見る", reading: "みる", meaning: "보다, (꿈을) 꾸다", type: 'verb', difficulty: 10, verb_info: '2타' },
        { id: 'darakwonverb_31', japanese: "聞く", reading: "きく", meaning: "듣다, 묻다", type: 'verb', difficulty: 10, verb_info: '1타' },
        { id: 'darakwonverb_32', japanese: "言う", reading: "いう", meaning: "말하다", type: 'verb', difficulty: 10, verb_info: '1타' },
        { id: 'darakwonverb_33', japanese: "食べる", reading: "たべる", meaning: "먹다", type: 'verb', difficulty: 10, verb_info: '2타' },
        { id: 'darakwonverb_34', japanese: "飲む", reading: "のむ", meaning: "마시다, 약을 먹다", type: 'verb', difficulty: 10, verb_info: '1타' },
        { id: 'darakwonverb_35', japanese: "噛む", reading: "かむ", meaning: "씹다, 물다", type: 'verb', difficulty: 28, verb_info: '1타' },
        { id: 'darakwonverb_36', japanese: "吸う", reading: "すう", meaning: "들이마시다, (담배를) 피우다, 흡수하다", type: 'verb', difficulty: 25, verb_info: '1타' },
        { id: 'darakwonverb_37', japanese: "読む", reading: "よむ", meaning: "읽다", type: 'verb', difficulty: 12, verb_info: '1타' },
        { id: 'darakwonverb_38', japanese: "書く", reading: "かく", meaning: "쓰다, 그리다", type: 'verb', difficulty: 12, verb_info: '1타' },
        { id: 'darakwonverb_39', japanese: "泣く", reading: "なく", meaning: "울다", type: 'verb', difficulty: 15, verb_info: '1자' },
        { id: 'darakwonverb_40', japanese: "笑う", reading: "わらう", meaning: "웃다, 비웃다", type: 'verb', difficulty: 18, verb_info: '1자' },
        { id: 'darakwonverb_41', japanese: "歩く", reading: "あるく", meaning: "걷다", type: 'verb', difficulty: 12, verb_info: '1자' },
        { id: 'darakwonverb_42', japanese: "走る", reading: "はしる", meaning: "달리다, (부정적으로) 쏠리다, 치우치다", type: 'verb', difficulty: 15, verb_info: '1자' },
        { id: 'darakwonverb_43', japanese: "跳ねる", reading: "はねる", meaning: "뛰어오르다, 튀기다, 들이받다", type: 'verb', difficulty: 36, verb_info: '2자' },
        { id: 'darakwonverb_44', japanese: "飛ぶ", reading: "とぶ", meaning: "날다, 건너뛰다, 누락되다", type: 'verb', difficulty: 15, verb_info: '1자' },
        { id: 'darakwonverb_45', japanese: "泳ぐ", reading: "およぐ", meaning: "헤엄치다", type: 'verb', difficulty: 18, verb_info: '1자' },
        { id: 'darakwonverb_46', japanese: "投げる", reading: "なげる", meaning: "던지다", type: 'verb', difficulty: 25, verb_info: '2타' },
        { id: 'darakwonverb_47', japanese: "蹴る", reading: "ける", meaning: "(발로) 차다", type: 'verb', difficulty: 28, verb_info: '1타' },
        { id: 'darakwonverb_48', japanese: "打つ", reading: "うつ", meaning: "치다, 부딪치다, 찌르다, (마음을) 울리다, (바둑을) 두다", type: 'verb', difficulty: 22, verb_info: '1타' },
        { id: 'darakwonverb_49', japanese: "思う", reading: "おもう", meaning: "(주관적/의지적) 생각하다", type: 'verb', difficulty: 18, verb_info: '1타' },
        { id: 'darakwonverb_50', japanese: "考える", reading: "かんがえる", meaning: "(이성적/객관적) 생각하다", type: 'verb', difficulty: 22, verb_info: '2타' },
        { id: 'darakwonverb_51', japanese: "悩む", reading: "なやむ", meaning: "고민하다", type: 'verb', difficulty: 28, verb_info: '1자' },
        { id: 'darakwonverb_52', japanese: "疑う", reading: "うたがう", meaning: "의심하다", type: 'verb', difficulty: 37, verb_info: '1타' },
        { id: 'darakwonverb_53', japanese: "落ち着く", reading: "おちつく", meaning: "진정되다, 정착하다", type: 'verb', difficulty: 30, verb_info: '1자' },
        { id: 'darakwonverb_54', japanese: "確かめる", reading: "たしかめる", meaning: "확인하다", type: 'verb', difficulty: 30, verb_info: '2타' },
        { id: 'darakwonverb_55', japanese: "信じる", reading: "しんじる", meaning: "믿다", type: 'verb', difficulty: 25, verb_info: '2타' },
        { id: 'darakwonverb_56', japanese: "痛む", reading: "いたむ", meaning: "아프다", type: 'verb', difficulty: 28, verb_info: '1자' },
        { id: 'darakwonverb_57', japanese: "傷む", reading: "いたむ", meaning: "(무생물이) 상하다, 망가지다", type: 'verb', difficulty: 32, verb_info: '1자' },
        { id: 'darakwonverb_58', japanese: "感じる", reading: "かんじる", meaning: "느끼다", type: 'verb', difficulty: 28, verb_info: '2타' },
        { id: 'darakwonverb_59', japanese: "染みる", reading: "しみる", meaning: "시리다, 스며들다", type: 'verb', difficulty: 42, verb_info: '2자' },
        { id: 'darakwonverb_60', japanese: "話す", reading: "はなす", meaning: "이야기하다, 말하다", type: 'verb', difficulty: 12, verb_info: '1타' },
        { id: 'darakwonverb_61', japanese: "しゃべる", reading: "しゃべる", meaning: "수다 떨다, 지껄이다", type: 'verb', difficulty: 26, verb_info: '1자' },
        { id: 'darakwonverb_62', japanese: "語る", reading: "かたる", meaning: "(감정, 서사를) 이야기하다", type: 'verb', difficulty: 32, verb_info: '1타' },
        { id: 'darakwonverb_63', japanese: "物語る", reading: "ものがたる", meaning: "(상황이 어떤 사실을) 말해주다", type: 'verb', difficulty: 44, verb_info: '1타' },
        { id: 'darakwonverb_64', japanese: "述べる", reading: "のべる", meaning: "진술하다, 서술하다", type: 'verb', difficulty: 38, verb_info: '2타' },
        { id: 'darakwonverb_65', japanese: "つぶやく", reading: "つぶやく", meaning: "중얼거리다", type: 'verb', difficulty: 42, verb_info: '1자' },
        { id: 'darakwonverb_66', japanese: "ささやく", reading: "ささやく", meaning: "속삭이다", type: 'verb', difficulty: 42, verb_info: '1자' },
        { id: 'darakwonverb_67', japanese: "どもる", reading: "どもる", meaning: "말을 더듬다", type: 'verb', difficulty: 48, verb_info: '1자' },
        { id: 'darakwonverb_68', japanese: "呼ぶ", reading: "よぶ", meaning: "부르다", type: 'verb', difficulty: 18, verb_info: '1타' },
        { id: 'darakwonverb_69', japanese: "叫ぶ", reading: "さけぶ", meaning: "외치다", type: 'verb', difficulty: 28, verb_info: '1자' },
        { id: 'darakwonverb_70', japanese: "黙る", reading: "だまる", meaning: "입 다물다", type: 'verb', difficulty: 33, verb_info: '1자' },
        { id: 'darakwonverb_71', japanese: "掛ける", reading: "かける", meaning: "걸다, 얹다, (전화를) 걸다, 잠그다, (폐를) 끼치다, (안경을) 쓰다 등", type: 'verb', difficulty: 22, verb_info: '2타' },
        { id: 'darakwonverb_72', japanese: "掛かる", reading: "かかる", meaning: "걸리다, (말, 유혹 등을) 걸어오다, (열쇠, 단추 등을) 채워지다", type: 'verb', difficulty: 22, verb_info: '1자' },
        { id: 'darakwonverb_73', japanese: "付ける", reading: "つける", meaning: "부착하다, 접착하다, 첨가하다, 기록하다, (실력, 습관 등) 붙이다", type: 'verb', difficulty: 20, verb_info: '2타' },
        { id: 'darakwonverb_74', japanese: "点ける", reading: "つける", meaning: "(불, 빛, 전기를) 켜다", type: 'verb', difficulty: 22, verb_info: '2타' },
        { id: 'darakwonverb_75', japanese: "消す", reading: "けす", meaning: "지우다, 없애다, 끄다", type: 'verb', difficulty: 18, verb_info: '1타' },
        { id: 'darakwonverb_76', japanese: "開ける", reading: "あける", meaning: "열다, (눈을) 뜨다", type: 'verb', difficulty: 15, verb_info: '2타' },
        { id: 'darakwonverb_77', japanese: "開く", reading: "あく", meaning: "열리다, (눈을) 뜨다", type: 'verb', difficulty: 18, verb_info: '1자' },
        { id: 'darakwonverb_78', japanese: "閉める", reading: "しめる", meaning: "닫다, 영업 종료하다", type: 'verb', difficulty: 15, verb_info: '2타' },
        { id: 'darakwonverb_79', japanese: "閉まる", reading: "しまる", meaning: "닫히다", type: 'verb', difficulty: 18, verb_info: '1자' },
        { id: 'darakwonverb_80', japanese: "取る", reading: "とる", meaning: "집다, 따다, 빼내다, 받아들이다", type: 'verb', difficulty: 15, verb_info: '1타' },
        { id: 'darakwonverb_81', japanese: "持つ", reading: "もつ", meaning: "가지다, 들다", type: 'verb', difficulty: 12, verb_info: '1타' },
        { id: 'darakwonverb_82', japanese: "押す", reading: "おす", meaning: "밀다, 누르다, (도장을) 찍다", type: 'verb', difficulty: 15, verb_info: '1타' },
        { id: 'darakwonverb_83', japanese: "引く", reading: "ひく", meaning: "당기다, 끌다, 빼다", type: 'verb', difficulty: 18, verb_info: '1타' },
        { id: 'darakwonverb_84', japanese: "引っ張る", reading: "ひっぱる", meaning: "잡아끌다, 연행하다", type: 'verb', difficulty: 28, verb_info: '1타' },
        { id: 'darakwonverb_85', japanese: "押さえる", reading: "おさえる", meaning: "누르다, (핵심을) 파악하다", type: 'verb', difficulty: 44, verb_info: '2타' },
        { id: 'darakwonverb_86', japanese: "撫でる", reading: "なでる", meaning: "쓰다듬다, 어루만지다", type: 'verb', difficulty: 38, verb_info: '2타' },
        { id: 'darakwonverb_87', japanese: "振る", reading: "ふる", meaning: "흔들다, (연인에게)(수동태로) 차이다", type: 'verb', difficulty: 26, verb_info: '1타' },
        { id: 'darakwonverb_88', japanese: "掴む", reading: "つかむ", meaning: "움켜쥐다, 손에 넣다, 파악하다", type: 'verb', difficulty: 34, verb_info: '1타' },
        { id: 'darakwonverb_89', japanese: "握る", reading: "にぎる", meaning: "쥐다, 장악하다", type: 'verb', difficulty: 32, verb_info: '1타' },
        { id: 'darakwonverb_90', japanese: "結ぶ", reading: "むすぶ", meaning: "매다, 관개를 맺다, 잇다", type: 'verb', difficulty: 30, verb_info: '1타' },
        { id: 'darakwonverb_91', japanese: "縛る", reading: "しばる", meaning: "묶다", type: 'verb', difficulty: 38, verb_info: '1타' },
        { id: 'darakwonverb_92', japanese: "触る", reading: "さわる", meaning: "닿다, 손대다", type: 'verb', difficulty: 27, verb_info: '1자' },
        { id: 'darakwonverb_93', japanese: "障る", reading: "さわる", meaning: "방해가 되다, 거슬리다", type: 'verb', difficulty: 42, verb_info: '1자' },
        { id: 'darakwonverb_94', japanese: "叩く", reading: "たたく", meaning: "때리다, 비난하다", type: 'verb', difficulty: 28, verb_info: '1타' },
        { id: 'darakwonverb_95', japanese: "追い払う", reading: "おいはらう", meaning: "내쫓다", type: 'verb', difficulty: 45, verb_info: '1타' },
        { id: 'darakwonverb_96', japanese: "貼る", reading: "はる", meaning: "(얇은 것을) 붙이다", type: 'verb', difficulty: 22, verb_info: '1타' },
        { id: 'darakwonverb_97', japanese: "塗る", reading: "ぬる", meaning: "칠하다, 바르다", type: 'verb', difficulty: 32, verb_info: '1타' },
        { id: 'darakwonverb_98', japanese: "縫う", reading: "ぬう", meaning: "꿰메다", type: 'verb', difficulty: 38, verb_info: '1타' },
        { id: 'darakwonverb_99', japanese: "捲る", reading: "めくる", meaning: "(종이 등을) 넘기다, 들추다", type: 'verb', difficulty: 42, verb_info: '1타' },
        { id: 'darakwonverb_100', japanese: "捲る", reading: "まくる", meaning: "걷어올리다", type: 'verb', difficulty: 42, verb_info: '1타' },
        { id: 'darakwonverb_101', japanese: "出す", reading: "だす", meaning: "내다, 제출하다", type: 'verb', difficulty: 12, verb_info: '1타' },
        { id: 'darakwonverb_102', japanese: "作る", reading: "つくる", meaning: "만들다", type: 'verb', difficulty: 12, verb_info: '1타' },
        { id: 'darakwonverb_103', japanese: "置く", reading: "おく", meaning: "놓다, (간격을) 두다", type: 'verb', difficulty: 15, verb_info: '1타' }
    ]
});
