registerVocabularySet({
    name: '일본어 필수 동사 500',
    words: [
        { id: 'darakwonverb_1', japanese: "寝る", reading: "ねる", meaning: "자다, 잠자리에 들다, 눕다", type: 'verb', difficulty: 12, verb_info: '2자' },
        { id: 'darakwonverb_2', japanese: "寝かす", reading: "ねかす", meaning: "(잠을) 재우다, 누이다", type: 'verb', difficulty: 32, verb_info: '1타' },
        { id: 'darakwonverb_3', japanese: "眠る", reading: "ねむる", meaning: "잠들다, 잠든 채 자다", type: 'verb', difficulty: 22, verb_info: '1자' },
        { id: 'darakwonverb_4', japanese: "覚める", reading: "さめる", meaning: "(잠, 취기, 꿈 등에서) 깨다", type: 'verb', difficulty: 28, verb_info: '2자' },
        { id: 'darakwonverb_5', japanese: "起きる", reading: "おきる", meaning: "일어나다", type: 'verb', difficulty: 12, verb_info: '2자' },
        { id: 'darakwonverb_6', japanese: "起こす", reading: "おこす", meaning: "(잠을) 깨우다, (쓰러진 것을) 일으키다", type: 'verb', difficulty: 18, verb_info: '1타' },
        { id: 'darakwonverb_7', japanese: "畳む", reading: "たたむ", meaning: "(이불 등을) 개다, (우산을) 접다, 걷어치우다", type: 'verb', difficulty: 34, verb_info: '1타' },
        { id: 'darakwonverb_8', japanese: "洗う", reading: "あらう", meaning: "씻다, (머리를) 감다, (빨래를) 빨다", type: 'verb', difficulty: 15, verb_info: '1타' },
        { id: 'darakwonverb_9', japanese: "剃る", reading: "そる", meaning: "깎다, 면도하다", type: 'verb', difficulty: 38, verb_info: '1타' },
        { id: 'darakwonverb_10', japanese: "磨く", reading: "みがく", meaning: "(표면을 문질러) 닦다, 윤을 내다", type: 'verb', difficulty: 22, verb_info: '1타' },
        { id: 'darakwonverb_11', japanese: "拭く", reading: "ふく", meaning: "(물기, 먼지 등을) 닦아 내다", type: 'verb', difficulty: 24, verb_info: '1타' },
        { id: 'darakwonverb_12', japanese: "休む", reading: "やすむ", meaning: "쉬다, 결석하다, 취침하다", type: 'verb', difficulty: 12, verb_info: '1자' },
        { id: 'darakwonverb_13', japanese: "明ける", reading: "あける", meaning: "(날이) 밝다, (해가) 바뀌다", type: 'verb', difficulty: 28, verb_info: '2자' },
        { id: 'darakwonverb_14', japanese: "暮れる", reading: "くれる", meaning: "저물다, 지새우다", type: 'verb', difficulty: 28, verb_info: '2자' },
        { id: 'darakwonverb_15', japanese: "沈む", reading: "しずむ", meaning: "가라앉다, (해/달이) 지다", type: 'verb', difficulty: 35, verb_info: '1자' },
        { id: 'darakwonverb_16', japanese: "吹く", reading: "ふく", meaning: "(바람이) 불다, (입으로/악기를) 불다, 허풍 떨다", type: 'verb', difficulty: 22, verb_info: '1자' },
        { id: 'darakwonverb_17', japanese: "降る", reading: "ふる", meaning: "(비 등이) 내리다", type: 'verb', difficulty: 15, verb_info: '1자' },
        { id: 'darakwonverb_18', japanese: "止む", reading: "やむ", meaning: "그치다, 멎다", type: 'verb', difficulty: 26, verb_info: '1자' },
        { id: 'darakwonverb_19', japanese: "凍る", reading: "こおる", meaning: "얼다", type: 'verb', difficulty: 30, verb_info: '1자' },
        { id: 'darakwonverb_20', japanese: "溶ける", reading: "とける", meaning: "녹다", type: 'verb', difficulty: 34, verb_info: '2자' },
        { id: 'darakwonverb_21', japanese: "光る", reading: "ひかる", meaning: "(물체가) 빛을 내다, 반짝이다", type: 'verb', difficulty: 24, verb_info: '1자' },
        { id: 'darakwonverb_22', japanese: "輝く", reading: "かがやく", meaning: "(강하고 눈부시게) 빛나다, 찬란하게 빛나다", type: 'verb', difficulty: 35, verb_info: '1자' },
        { id: 'darakwonverb_23', japanese: "晴れる", reading: "はれる", meaning: "맑게 개다, 마음이 밝아지다", type: 'verb', difficulty: 18, verb_info: '2자' },
        { id: 'darakwonverb_24', japanese: "曇る", reading: "くもる", meaning: "(날씨가) 흐려지다, 희미해지다", type: 'verb', difficulty: 18, verb_info: '1자' },
        { id: 'darakwonverb_25', japanese: "漏れる", reading: "もれる", meaning: "(물/빛/비밀 등이) 새다", type: 'verb', difficulty: 36, verb_info: '2자' },
        { id: 'darakwonverb_26', japanese: "鳴る", reading: "なる", meaning: "울리다", type: 'verb', difficulty: 22, verb_info: '1자' },
        { id: 'darakwonverb_27', japanese: "続ける", reading: "つづける", meaning: "계속하다", type: 'verb', difficulty: 24, verb_info: '2타' },
        { id: 'darakwonverb_28', japanese: "遭う", reading: "あう", meaning: "(일을) 당하다, 겪다", type: 'verb', difficulty: 38, verb_info: '1자' },
        { id: 'darakwonverb_29', japanese: "喜ぶ", reading: "よろこぶ", meaning: "기뻐하다", type: 'verb', difficulty: 26, verb_info: '1자' },
        { id: 'darakwonverb_30', japanese: "見る", reading: "みる", meaning: "보다, (꿈을) 꾸다", type: 'verb', difficulty: 10, verb_info: '2타' },
        { id: 'darakwonverb_31', japanese: "聞く", reading: "きく", meaning: "듣다, 묻다", type: 'verb', difficulty: 10, verb_info: '1타' },
        { id: 'darakwonverb_32', japanese: "言う", reading: "いう", meaning: "말하다", type: 'verb', difficulty: 10, verb_info: '1타' },
        { id: 'darakwonverb_33', japanese: "食べる", reading: "たべる", meaning: "먹다", type: 'verb', difficulty: 10, verb_info: '2타' },
        { id: 'darakwonverb_34', japanese: "飲む", reading: "のむ", meaning: "마시다, 약을 먹다", type: 'verb', difficulty: 10, verb_info: '1타' },
        { id: 'darakwonverb_35', japanese: "噛む", reading: "かむ", meaning: "씹다, 물다", type: 'verb', difficulty: 28, verb_info: '1타' },
        { id: 'darakwonverb_36', japanese: "吸う", reading: "すう", meaning: "들이마시다, (담배를) 피우다, 흡수하다", type: 'verb', difficulty: 25, verb_info: '1타' },
        { id: 'darakwonverb_37', japanese: "読む", reading: "よむ", meaning: "읽다", type: 'verb', difficulty: 12, verb_info: '1타' },
        { id: 'darakwonverb_38', japanese: "書く", reading: "かく", meaning: "쓰다, 그리다", type: 'verb', difficulty: 12, verb_info: '1타' },
        { id: 'darakwonverb_39', japanese: "泣く", reading: "なく", meaning: "울다", type: 'verb', difficulty: 15, verb_info: '1자' },
        { id: 'darakwonverb_40', japanese: "笑う", reading: "わらう", meaning: "웃다, 비웃다", type: 'verb', difficulty: 18, verb_info: '1자' },
        { id: 'darakwonverb_41', japanese: "歩く", reading: "あるく", meaning: "걷다", type: 'verb', difficulty: 12, verb_info: '1자' },
        { id: 'darakwonverb_42', japanese: "走る", reading: "はしる", meaning: "달리다, (부정적으로) 쏠리다, 치우치다", type: 'verb', difficulty: 15, verb_info: '1자' },
        { id: 'darakwonverb_43', japanese: "跳ねる", reading: "はねる", meaning: "뛰어오르다, 튀기다, 들이받다", type: 'verb', difficulty: 36, verb_info: '2자' },
        { id: 'darakwonverb_44', japanese: "飛ぶ", reading: "とぶ", meaning: "날다, 건너뛰다, 누락되다", type: 'verb', difficulty: 15, verb_info: '1자' },
        { id: 'darakwonverb_45', japanese: "泳ぐ", reading: "およぐ", meaning: "헤엄치다", type: 'verb', difficulty: 18, verb_info: '1자' },
        { id: 'darakwonverb_46', japanese: "投げる", reading: "なげる", meaning: "던지다", type: 'verb', difficulty: 25, verb_info: '2타' },
        { id: 'darakwonverb_47', japanese: "蹴る", reading: "ける", meaning: "(발로) 차다", type: 'verb', difficulty: 28, verb_info: '1타' },
        { id: 'darakwonverb_48', japanese: "打つ", reading: "うつ", meaning: "치다, 부딪치다, 찌르다, (마음을) 울리다, (바둑을) 두다", type: 'verb', difficulty: 22, verb_info: '1타' },
        { id: 'darakwonverb_49', japanese: "思う", reading: "おもう", meaning: "(주관적/의지적) 생각하다", type: 'verb', difficulty: 18, verb_info: '1타' },
        { id: 'darakwonverb_50', japanese: "考える", reading: "かんがえる", meaning: "(이성적/객관적) 생각하다", type: 'verb', difficulty: 22, verb_info: '2타' },
        { id: 'darakwonverb_51', japanese: "悩む", reading: "なやむ", meaning: "고민하다", type: 'verb', difficulty: 28, verb_info: '1자' },
        { id: 'darakwonverb_52', japanese: "疑う", reading: "うたがう", meaning: "의심하다", type: 'verb', difficulty: 37, verb_info: '1타' },
        { id: 'darakwonverb_53', japanese: "落ち着く", reading: "おちつく", meaning: "진정되다, 정착하다", type: 'verb', difficulty: 30, verb_info: '1자' },
        { id: 'darakwonverb_54', japanese: "確かめる", reading: "たしかめる", meaning: "확인하다", type: 'verb', difficulty: 30, verb_info: '2타' },
        { id: 'darakwonverb_55', japanese: "信じる", reading: "しんじる", meaning: "믿다", type: 'verb', difficulty: 25, verb_info: '2타' },
        { id: 'darakwonverb_56', japanese: "痛む", reading: "いたむ", meaning: "아프다", type: 'verb', difficulty: 28, verb_info: '1자' },
        { id: 'darakwonverb_57', japanese: "傷む", reading: "いたむ", meaning: "(무생물이) 상하다, 망가지다", type: 'verb', difficulty: 32, verb_info: '1자' },
        { id: 'darakwonverb_58', japanese: "感じる", reading: "かんじる", meaning: "느끼다", type: 'verb', difficulty: 28, verb_info: '2타' },
        { id: 'darakwonverb_59', japanese: "染みる", reading: "しみる", meaning: "시리다, 스며들다", type: 'verb', difficulty: 42, verb_info: '2자' },
        { id: 'darakwonverb_60', japanese: "話す", reading: "はなす", meaning: "이야기하다, 말하다", type: 'verb', difficulty: 12, verb_info: '1타' },
        { id: 'darakwonverb_61', japanese: "しゃべる", reading: "しゃべる", meaning: "수다 떨다, 지껄이다", type: 'verb', difficulty: 26, verb_info: '1자' },
        { id: 'darakwonverb_62', japanese: "語る", reading: "かたる", meaning: "(감정, 서사를) 이야기하다", type: 'verb', difficulty: 32, verb_info: '1타' },
        { id: 'darakwonverb_63', japanese: "物語る", reading: "ものがたる", meaning: "(상황이 어떤 사실을) 말해주다", type: 'verb', difficulty: 44, verb_info: '1타' },
        { id: 'darakwonverb_64', japanese: "述べる", reading: "のべる", meaning: "진술하다, 서술하다", type: 'verb', difficulty: 38, verb_info: '2타' },
        { id: 'darakwonverb_65', japanese: "つぶやく", reading: "つぶやく", meaning: "중얼거리다", type: 'verb', difficulty: 42, verb_info: '1자' },
        { id: 'darakwonverb_66', japanese: "ささやく", reading: "ささやく", meaning: "속삭이다", type: 'verb', difficulty: 42, verb_info: '1자' },
        { id: 'darakwonverb_67', japanese: "どもる", reading: "どもる", meaning: "말을 더듬다", type: 'verb', difficulty: 48, verb_info: '1자' },
        { id: 'darakwonverb_68', japanese: "呼ぶ", reading: "よぶ", meaning: "부르다", type: 'verb', difficulty: 18, verb_info: '1타' },
        { id: 'darakwonverb_69', japanese: "叫ぶ", reading: "さけぶ", meaning: "외치다", type: 'verb', difficulty: 28, verb_info: '1자' },
        { id: 'darakwonverb_70', japanese: "黙る", reading: "だまる", meaning: "입 다물다", type: 'verb', difficulty: 33, verb_info: '1자' },
        { id: 'darakwonverb_71', japanese: "掛ける", reading: "かける", meaning: "(벽 등에) 걸다, 걸쳐 두다, (전화를) 걸다, (자물쇠를) 잠그다, (안경을) 쓰다 등", type: 'verb', difficulty: 22, verb_info: '2타' },
        { id: 'darakwonverb_72', japanese: "掛かる", reading: "かかる", meaning: "(벽 등에) 걸리다, (말, 유혹 등을) 걸어오다, (열쇠, 단추 등이) 채워지다", type: 'verb', difficulty: 22, verb_info: '1자' },
        { id: 'darakwonverb_73', japanese: "付ける", reading: "つける", meaning: "(붙여서) 달다, 덧붙이다, 기록하다, (실력, 습관 등을) 몸에 익히다", type: 'verb', difficulty: 20, verb_info: '2타' },
        { id: 'darakwonverb_74', japanese: "点ける", reading: "つける", meaning: "(불, 전등 등을) 켜다", type: 'verb', difficulty: 22, verb_info: '2타' },
        { id: 'darakwonverb_75', japanese: "消す", reading: "けす", meaning: "지우다, 없애다, 끄다", type: 'verb', difficulty: 18, verb_info: '1타' },
        { id: 'darakwonverb_76', japanese: "開ける", reading: "あける", meaning: "(문, 뚜껑 등을) 열다, (눈을) 뜨다", type: 'verb', difficulty: 15, verb_info: '2타' },
        { id: 'darakwonverb_77', japanese: "開く", reading: "あく", meaning: "(문, 뚜껑 등이) 열리다, (눈이) 떠지다", type: 'verb', difficulty: 18, verb_info: '1자' },
        { id: 'darakwonverb_78', japanese: "閉める", reading: "しめる", meaning: "닫다, 영업 종료하다", type: 'verb', difficulty: 15, verb_info: '2타' },
        { id: 'darakwonverb_79', japanese: "閉まる", reading: "しまる", meaning: "닫히다", type: 'verb', difficulty: 18, verb_info: '1자' },
        { id: 'darakwonverb_80', japanese: "取る", reading: "とる", meaning: "집다, 따다, 떼어 내다, 받아들이다", type: 'verb', difficulty: 15, verb_info: '1타' },
        { id: 'darakwonverb_81', japanese: "持つ", reading: "もつ", meaning: "가지다, 들다", type: 'verb', difficulty: 12, verb_info: '1타' },
        { id: 'darakwonverb_82', japanese: "押す", reading: "おす", meaning: "밀다, 눌러서 작동시키다, (도장을) 찍다", type: 'verb', difficulty: 15, verb_info: '1타' },
        { id: 'darakwonverb_83', japanese: "引く", reading: "ひく", meaning: "당기다, 끌다, 빼다", type: 'verb', difficulty: 18, verb_info: '1타' },
        { id: 'darakwonverb_84', japanese: "引っ張る", reading: "ひっぱる", meaning: "잡아끌다, 연행하다", type: 'verb', difficulty: 28, verb_info: '1타' },
        { id: 'darakwonverb_85', japanese: "押さえる", reading: "おさえる", meaning: "꾹 눌러 고정하다, (핵심을) 파악하다", type: 'verb', difficulty: 44, verb_info: '2타' },
        { id: 'darakwonverb_86', japanese: "撫でる", reading: "なでる", meaning: "쓰다듬다, 어루만지다", type: 'verb', difficulty: 38, verb_info: '2타' },
        { id: 'darakwonverb_87', japanese: "振る", reading: "ふる", meaning: "좌우로 흔들다, (연인에게) 차다", type: 'verb', difficulty: 26, verb_info: '1타' },
        { id: 'darakwonverb_88', japanese: "掴む", reading: "つかむ", meaning: "움켜쥐다, 손에 넣다, 파악하다", type: 'verb', difficulty: 34, verb_info: '1타' },
        { id: 'darakwonverb_89', japanese: "握る", reading: "にぎる", meaning: "쥐다, 장악하다", type: 'verb', difficulty: 32, verb_info: '1타' },
        { id: 'darakwonverb_90', japanese: "結ぶ", reading: "むすぶ", meaning: "매다, 묶다, 이어 맺다", type: 'verb', difficulty: 30, verb_info: '1타' },
        { id: 'darakwonverb_91', japanese: "縛る", reading: "しばる", meaning: "묶다", type: 'verb', difficulty: 38, verb_info: '1타' },
        { id: 'darakwonverb_92', japanese: "触る", reading: "さわる", meaning: "닿다, 손대다", type: 'verb', difficulty: 27, verb_info: '1자' },
        { id: 'darakwonverb_93', japanese: "障る", reading: "さわる", meaning: "방해가 되다, 거슬리다", type: 'verb', difficulty: 42, verb_info: '1자' },
        { id: 'darakwonverb_94', japanese: "叩く", reading: "たたく", meaning: "때리다, 비난하다", type: 'verb', difficulty: 28, verb_info: '1타' },
        { id: 'darakwonverb_95', japanese: "追い払う", reading: "おいはらう", meaning: "내쫓다", type: 'verb', difficulty: 45, verb_info: '1타' },
        { id: 'darakwonverb_96', japanese: "貼る", reading: "はる", meaning: "(얇은 것을) 붙이다", type: 'verb', difficulty: 22, verb_info: '1타' },
        { id: 'darakwonverb_97', japanese: "塗る", reading: "ぬる", meaning: "칠하다, 바르다", type: 'verb', difficulty: 32, verb_info: '1타' },
        { id: 'darakwonverb_98', japanese: "縫う", reading: "ぬう", meaning: "꿰메다", type: 'verb', difficulty: 38, verb_info: '1타' },
        { id: 'darakwonverb_99', japanese: "捲る", reading: "めくる", meaning: "(종이 등을) 넘기다, 들추다", type: 'verb', difficulty: 42, verb_info: '1타' },
        { id: 'darakwonverb_100', japanese: "捲る", reading: "まくる", meaning: "걷어올리다", type: 'verb', difficulty: 42, verb_info: '1타' },
        { id: 'darakwonverb_101', japanese: "出す", reading: "だす", meaning: "내다, 제출하다", type: 'verb', difficulty: 12, verb_info: '1타' },
        { id: 'darakwonverb_102', japanese: "作る", reading: "つくる", meaning: "만들다", type: 'verb', difficulty: 12, verb_info: '1타' },
        { id: 'darakwonverb_103', japanese: "置く", reading: "おく", meaning: "놓다, (간격을) 두다", type: 'verb', difficulty: 15, verb_info: '1타' },
        { id: 'darakwonverb_104', japanese: "立つ", reading: "たつ", meaning: "서다", type: 'verb', difficulty: 12, verb_info: '1자' },
        { id: 'darakwonverb_105', japanese: "立ち上がる", reading: "たちあがる", meaning: "일어서다", type: 'verb', difficulty: 18, verb_info: '1자' },
        { id: 'darakwonverb_106', japanese: "座る", reading: "すわる", meaning: "앉다", type: 'verb', difficulty: 12, verb_info: '1자' },
        { id: 'darakwonverb_107', japanese: "しゃがむ", reading: "しゃがむ", meaning: "웅크리다", type: 'verb', difficulty: 30, verb_info: '1자' },
        { id: 'darakwonverb_108', japanese: "伏せる", reading: "ふせる", meaning: "엎드리다, 엎어 놓다, 숨기다", type: 'verb', difficulty: 32, verb_info: '2타' },
        { id: 'darakwonverb_109', japanese: "横になる", reading: "よこになる", meaning: "드러눕다", type: 'verb', difficulty: 18, verb_info: '1자' },
        { id: 'darakwonverb_110', japanese: "曲げる", reading: "まげる", meaning: "굽히다", type: 'verb', difficulty: 28, verb_info: '2타' },
        { id: 'darakwonverb_111', japanese: "組む", reading: "くむ", meaning: "(팔짱을) 끼다, (끈 등을)짜다, 구성하다", type: 'verb', difficulty: 29, verb_info: '1타' },
        { id: 'darakwonverb_112', japanese: "踏む", reading: "ふむ", meaning: "밟다", type: 'verb', difficulty: 18, verb_info: '1타' },
        { id: 'darakwonverb_113', japanese: "悲しむ", reading: "かなしむ", meaning: "슬퍼하다", type: 'verb', difficulty: 28, verb_info: '1자' },
        { id: 'darakwonverb_114', japanese: "悼む", reading: "いたむ", meaning: "애도하다", type: 'verb', difficulty: 40, verb_info: '1타' },
        { id: 'darakwonverb_115', japanese: "楽しむ", reading: "たのしむ", meaning: "즐기다", type: 'verb', difficulty: 22, verb_info: '1타' },
        { id: 'darakwonverb_116', japanese: "好む", reading: "このむ", meaning: "좋아하다", type: 'verb', difficulty: 32, verb_info: '1타' },
        { id: 'darakwonverb_117', japanese: "嫌う", reading: "きらう", meaning: "싫어하다", type: 'verb', difficulty: 30, verb_info: '1타' },
        { id: 'darakwonverb_118', japanese: "憎む", reading: "にくむ", meaning: "미워하다", type: 'verb', difficulty: 34, verb_info: '1타' },
        { id: 'darakwonverb_119', japanese: "恐れる", reading: "おそれる", meaning: "두려워하다", type: 'verb', difficulty: 34, verb_info: '2타' },
        { id: 'darakwonverb_120', japanese: "惜しむ", reading: "おしむ", meaning: "소중히 여기다, 아쉬워하다", type: 'verb', difficulty: 36, verb_info: '1타' },
        { id: 'darakwonverb_121', japanese: "恨む", reading: "うらむ", meaning: "원망하다", type: 'verb', difficulty: 36, verb_info: '1타' },
        { id: 'darakwonverb_122', japanese: "驚く", reading: "おどろく", meaning: "놀라다", type: 'verb', difficulty: 28, verb_info: '1자' },
        { id: 'darakwonverb_123', japanese: "驚かす", reading: "おどろかす", meaning: "놀라게 하다", type: 'verb', difficulty: 30, verb_info: '1타' },
        { id: 'darakwonverb_124', japanese: "びっくりする", reading: "びっくりする", meaning: "깜짝 놀라다", type: 'verb', difficulty: 18, verb_info: '3자' },
        { id: 'darakwonverb_125', japanese: "ときめく", reading: "ときめく", meaning: "설레다", type: 'verb', difficulty: 30, verb_info: '1자' },
        { id: 'darakwonverb_126', japanese: "可愛がる", reading: "かわいがる", meaning: "귀여워하다", type: 'verb', difficulty: 34, verb_info: '1타' },
        { id: 'darakwonverb_127', japanese: "飽きる", reading: "あきる", meaning: "질리다", type: 'verb', difficulty: 35, verb_info: '2자' },
        { id: 'darakwonverb_128', japanese: "呆れる", reading: "あきれる", meaning: "어이가 없다", type: 'verb', difficulty: 32, verb_info: '2자' },
        { id: 'darakwonverb_129', japanese: "怒る", reading: "おこる", meaning: "화내다, 꾸짖다", type: 'verb', difficulty: 22, verb_info: '1자' },
        { id: 'darakwonverb_130', japanese: "叱る", reading: "しかる", meaning: "꾸짖다", type: 'verb', difficulty: 24, verb_info: '1타' },
        { id: 'darakwonverb_131', japanese: "褒める", reading: "ほめる", meaning: "칭찬하다", type: 'verb', difficulty: 18, verb_info: '2타' },
        { id: 'darakwonverb_132', japanese: "いじめる", reading: "いじめる", meaning: "(악의적으로) 괴롭히다", type: 'verb', difficulty: 26, verb_info: '2타' },
        { id: 'darakwonverb_133', japanese: "甘える", reading: "あまえる", meaning: "응석부리다, (호의를) 스스럼없이 받아들이다", type: 'verb', difficulty: 36, verb_info: '2자' },
        { id: 'darakwonverb_134', japanese: "甘やかす", reading: "あまやかす", meaning: "응석을 받아주다", type: 'verb', difficulty: 38, verb_info: '1타' },
        { id: 'darakwonverb_135', japanese: "責める", reading: "せめる", meaning: "비난하다", type: 'verb', difficulty: 30, verb_info: '2타' },
        { id: 'darakwonverb_136', japanese: "からかう", reading: "からかう", meaning: "놀리다", type: 'verb', difficulty: 26, verb_info: '1타' },
        { id: 'darakwonverb_137', japanese: "ふざける", reading: "ふざける", meaning: "희롱하다", type: 'verb', difficulty: 26, verb_info: '2자' },
        { id: 'darakwonverb_138', japanese: "狂う", reading: "くるう", meaning: "미치다, (예상이) 어긋나다", type: 'verb', difficulty: 34, verb_info: '1자' },
        { id: 'darakwonverb_139', japanese: "睨む", reading: "にらむ", meaning: "노려보다, 짐작하다", type: 'verb', difficulty: 36, verb_info: '1타' },
        { id: 'darakwonverb_140', japanese: "微笑む", reading: "ほほえむ", meaning: "미소 짓다", type: 'verb', difficulty: 38, verb_info: '1자' },
        { id: 'darakwonverb_141', japanese: "悩ます", reading: "なやます", meaning: "골치 아프게 하다, 시달리게 하다", type: 'verb', difficulty: 40, verb_info: '1타' },
        { id: 'darakwonverb_142', japanese: "苦しむ", reading: "くるしむ", meaning: "고생하다", type: 'verb', difficulty: 30, verb_info: '1자' },
        { id: 'darakwonverb_143', japanese: "迷う", reading: "まよう", meaning: "헤매다, 망설이다", type: 'verb', difficulty: 22, verb_info: '1자' },
        { id: 'darakwonverb_144', japanese: "戸惑う", reading: "とまどう", meaning: "어리둥절하다", type: 'verb', difficulty: 34, verb_info: '1자' },
        { id: 'darakwonverb_145', japanese: "慌てる", reading: "あわてる", meaning: "허둥지둥하다", type: 'verb', difficulty: 36, verb_info: '2자' },
        { id: 'darakwonverb_146', japanese: "うろたえる", reading: "うろたえる", meaning: "(꼴사납게) 당황하다", type: 'verb', difficulty: 42, verb_info: '2자' },
        { id: 'darakwonverb_147', japanese: "うろつく", reading: "うろつく", meaning: "서성거리다", type: 'verb', difficulty: 34, verb_info: '1자' },
        { id: 'darakwonverb_148', japanese: "焦る", reading: "あせる", meaning: "초조해하다", type: 'verb', difficulty: 34, verb_info: '1자' },
        { id: 'darakwonverb_149', japanese: "困る", reading: "こまる", meaning: "곤란하다", type: 'verb', difficulty: 18, verb_info: '1자' },
        { id: 'darakwonverb_150', japanese: "ためらう", reading: "ためらう", meaning: "주저하다", type: 'verb', difficulty: 36, verb_info: '1자' },
        { id: 'darakwonverb_151', japanese: "頼る", reading: "たよる", meaning: "의지하다", type: 'verb', difficulty: 36, verb_info: '1자' },
        { id: 'darakwonverb_152', japanese: "望む", reading: "のぞむ", meaning: "(목표로서) 바라다", type: 'verb', difficulty: 30, verb_info: '1타' },
        { id: 'darakwonverb_153', japanese: "願う", reading: "ねがう", meaning: "기원하다", type: 'verb', difficulty: 28, verb_info: '1타' },
        { id: 'darakwonverb_154', japanese: "求める", reading: "もとめる", meaning: "찾다, 요구하다", type: 'verb', difficulty: 32, verb_info: '2타' },
        { id: 'darakwonverb_155', japanese: "祈る", reading: "いのる", meaning: "기도하다", type: 'verb', difficulty: 30, verb_info: '1타' },
        { id: 'darakwonverb_156', japanese: "諦める", reading: "あきらめる", meaning: "포기하다", type: 'verb', difficulty: 30, verb_info: '2타' },
        { id: 'darakwonverb_157', japanese: "慰める", reading: "なぐさめる", meaning: "위로하다", type: 'verb', difficulty: 46, verb_info: '2타' },
        { id: 'darakwonverb_158', japanese: "謝る", reading: "あやまる", meaning: "사과하다", type: 'verb', difficulty: 18, verb_info: '1자' },
        { id: 'darakwonverb_159', japanese: "許す", reading: "ゆるす", meaning: "용서하다, 허락하다", type: 'verb', difficulty: 34, verb_info: '1타' },
        { id: 'darakwonverb_160', japanese: "抱く", reading: "いだく", meaning: "(생각을) 품다", type: 'verb', difficulty: 36, verb_info: '1타' },
        { id: 'darakwonverb_161', japanese: "ある", reading: "ある", meaning: "(사물, 식물이) 있다", type: 'verb', difficulty: 10, verb_info: '1자' },
        { id: 'darakwonverb_162', japanese: "いる", reading: "いる", meaning: "(사람, 동물이) 있다", type: 'verb', difficulty: 10, verb_info: '2자' },
        { id: 'darakwonverb_163', japanese: "生む", reading: "うむ", meaning: "낳다", type: 'verb', difficulty: 24, verb_info: '1타' },
        { id: 'darakwonverb_164', japanese: "生まれる", reading: "うまれる", meaning: "태어나다", type: 'verb', difficulty: 18, verb_info: '2자' },
        { id: 'darakwonverb_165', japanese: "生きる", reading: "いきる", meaning: "(생명의 의미로) 살다", type: 'verb', difficulty: 15, verb_info: '2자' },
        { id: 'darakwonverb_166', japanese: "住む", reading: "すむ", meaning: "(주거의 의미로) 살다", type: 'verb', difficulty: 15, verb_info: '1자' },
        { id: 'darakwonverb_167', japanese: "住まう", reading: "すまう", meaning: "거주하다", type: 'verb', difficulty: 38, verb_info: '1자' },
        { id: 'darakwonverb_168', japanese: "暮らす", reading: "くらす", meaning: "(생활의 의미로) 살다", type: 'verb', difficulty: 18, verb_info: '1자' },
        { id: 'darakwonverb_169', japanese: "育つ", reading: "そだつ", meaning: "자라다", type: 'verb', difficulty: 24, verb_info: '1자' },
        { id: 'darakwonverb_170', japanese: "育てる", reading: "そだてる", meaning: "기르다", type: 'verb', difficulty: 25, verb_info: '2타' },
        { id: 'darakwonverb_171', japanese: "死ぬ", reading: "しぬ", meaning: "죽다", type: 'verb', difficulty: 12, verb_info: '1자' },
        { id: 'darakwonverb_172', japanese: "亡くなる", reading: "なくなる", meaning: "(죽음) 돌아가시다", type: 'verb', difficulty: 28, verb_info: '1자' },
        { id: 'darakwonverb_173', japanese: "咲く", reading: "さく", meaning: "(꽃이) 피다", type: 'verb', difficulty: 18, verb_info: '1자' },
        { id: 'darakwonverb_174', japanese: "散る", reading: "ちる", meaning: "(꽃, 잎이) 지다, 흩날리다, (주의가) 산란해지다", type: 'verb', difficulty: 30, verb_info: '1자' },
        { id: 'darakwonverb_175', japanese: "茂る", reading: "しげる", meaning: "우거지다", type: 'verb', difficulty: 34, verb_info: '1자' },
        { id: 'darakwonverb_176', japanese: "枯れる", reading: "かれる", meaning: "(식물이) 시들어 마르다", type: 'verb', difficulty: 38, verb_info: '2자' },
        { id: 'darakwonverb_177', japanese: "蒔く", reading: "まく", meaning: "파종하다", type: 'verb', difficulty: 40, verb_info: '1타' },
        { id: 'darakwonverb_178', japanese: "芽を出す", reading: "めをだす", meaning: "싹을 내다", type: 'verb', difficulty: 34, verb_info: '1자' },
        { id: 'darakwonverb_179', japanese: "実る", reading: "みのる", meaning: "열매를 맺다", type: 'verb', difficulty: 30, verb_info: '1자' },
        { id: 'darakwonverb_180', japanese: "熟す", reading: "じゅくす", meaning: "(과일이) 익다, (기회가) 무르익다", type: 'verb', difficulty: 36, verb_info: '1자' },
        { id: 'darakwonverb_181', japanese: "萎む", reading: "しぼむ", meaning: "(꽃, 잎, 풍선 등이) 오그라들며 시들다", type: 'verb', difficulty: 40, verb_info: '1자' },
        { id: 'darakwonverb_182', japanese: "植える", reading: "うえる", meaning: "심다", type: 'verb', difficulty: 28, verb_info: '2타' },
        { id: 'darakwonverb_183', japanese: "生える", reading: "はえる", meaning: "(수염, 풀 등이) 나다, 자라다", type: 'verb', difficulty: 32, verb_info: '2자' },
        { id: 'darakwonverb_184', japanese: "飼う", reading: "かう", meaning: "(동물을) 기르다", type: 'verb', difficulty: 20, verb_info: '1타' },
        { id: 'darakwonverb_185', japanese: "鳴く", reading: "なく", meaning: "(새, 벌레, 짐승 등이) 울다", type: 'verb', difficulty: 22, verb_info: '1자' },
        { id: 'darakwonverb_186', japanese: "吠える", reading: "ほえる", meaning: "짖다", type: 'verb', difficulty: 24, verb_info: '2자' },
        { id: 'darakwonverb_187', japanese: "吼える", reading: "ほえる", meaning: "포효하다", type: 'verb', difficulty: 38, verb_info: '2자' },
        { id: 'darakwonverb_188', japanese: "馴れる", reading: "なれる", meaning: "사람을 따르다", type: 'verb', difficulty: 40, verb_info: '2자' },
        { id: 'darakwonverb_189', japanese: "着る", reading: "きる", meaning: "(허리 위, 또는 전신 옷을) 입다", type: 'verb', difficulty: 12, verb_info: '2타' },
        { id: 'darakwonverb_190', japanese: "脱ぐ", reading: "ぬぐ", meaning: "벗다", type: 'verb', difficulty: 24, verb_info: '1타' },
        { id: 'darakwonverb_191', japanese: "履く", reading: "はく", meaning: "(발에) 신다", type: 'verb', difficulty: 15, verb_info: '1타' },
        { id: 'darakwonverb_192', japanese: "穿く", reading: "はく", meaning: "(허리 아래로) 입다", type: 'verb', difficulty: 28, verb_info: '1타' },
        { id: 'darakwonverb_193', japanese: "はめる", reading: "はめる", meaning: "(장갑, 장신구 등을) 끼다", type: 'verb', difficulty: 20, verb_info: '2타' },
        { id: 'darakwonverb_194', japanese: "被る", reading: "かぶる", meaning: "(머리에) 쓰다", type: 'verb', difficulty: 18, verb_info: '1타' },
        { id: 'darakwonverb_195', japanese: "被せる", reading: "かぶせる", meaning: "씌우다", type: 'verb', difficulty: 28, verb_info: '2타' },
        { id: 'darakwonverb_196', japanese: "飾る", reading: "かざる", meaning: "장식하다", type: 'verb', difficulty: 30, verb_info: '1타' },
        { id: 'darakwonverb_197', japanese: "外す", reading: "はずす", meaning: "(장착/고정을) 떼다, 제외하다, 빗나가다", type: 'verb', difficulty: 26, verb_info: '1타' },
        { id: 'darakwonverb_198', japanese: "巻く", reading: "まく", meaning: "감다, 말다, 두르다", type: 'verb', difficulty: 20, verb_info: '1타' },
        { id: 'darakwonverb_199', japanese: "差す", reading: "さす", meaning: "가리다, (우산을) 쓰다", type: 'verb', difficulty: 20, verb_info: '1타' },
        { id: 'darakwonverb_200', japanese: "切る", reading: "きる", meaning: "자르다", type: 'verb', difficulty: 15, verb_info: '1타' },
        { id: 'darakwonverb_201', japanese: "刻む", reading: "きざむ", meaning: "잘게 썰다, 새기다, 명심하다", type: 'verb', difficulty: 30, verb_info: '1타' },
        { id: 'darakwonverb_202', japanese: "むく", reading: "むく", meaning: "(껍질을) 까다", type: 'verb', difficulty: 18, verb_info: '1타' },
        { id: 'darakwonverb_203', japanese: "揚げる", reading: "あげる", meaning: "튀기다, (깃발을) 올리다", type: 'verb', difficulty: 32, verb_info: '2타' },
        { id: 'darakwonverb_204', japanese: "炒める", reading: "いためる", meaning: "기름에 볶다", type: 'verb', difficulty: 30, verb_info: '2타' },
        { id: 'darakwonverb_205', japanese: "煎る", reading: "いる", meaning: "(기름 없이) 볶다", type: 'verb', difficulty: 34, verb_info: '1타' },
        { id: 'darakwonverb_206', japanese: "煮る", reading: "にる", meaning: "(재료를) 끓이다", type: 'verb', difficulty: 20, verb_info: '2타' },
        { id: 'darakwonverb_207', japanese: "ゆでる", reading: "ゆでる", meaning: "삶다", type: 'verb', difficulty: 18, verb_info: '2타' },
        { id: 'darakwonverb_208', japanese: "沸く", reading: "わく", meaning: "끓다", type: 'verb', difficulty: 22, verb_info: '1자' },
        { id: 'darakwonverb_209', japanese: "沸かす", reading: "わかす", meaning: "(액체를) 끓이다", type: 'verb', difficulty: 22, verb_info: '1타' },
        { id: 'darakwonverb_210', japanese: "焼く", reading: "やく", meaning: "굽다", type: 'verb', difficulty: 22, verb_info: '1타' },
        { id: 'darakwonverb_211', japanese: "焼ける", reading: "やける", meaning: "구워지다, (햇볕 등에) 타다", type: 'verb', difficulty: 28, verb_info: '2자' },
        { id: 'darakwonverb_212', japanese: "和える", reading: "あえる", meaning: "무치다, 버무리다", type: 'verb', difficulty: 34, verb_info: '2타' },
        { id: 'darakwonverb_213', japanese: "蒸す", reading: "むす", meaning: "찌다, 후텁지근하다", type: 'verb', difficulty: 30, verb_info: '1타' },
        { id: 'darakwonverb_214', japanese: "漬ける", reading: "つける", meaning: "담그다, 절이다", type: 'verb', difficulty: 32, verb_info: '2타' },
        { id: 'darakwonverb_215', japanese: "炊く", reading: "たく", meaning: "밥을 짓다", type: 'verb', difficulty: 28, verb_info: '1타' },
        { id: 'darakwonverb_216', japanese: "焦げる", reading: "こげる", meaning: "(식재료 등이) 타다, 그을리다", type: 'verb', difficulty: 39, verb_info: '2자' },
        { id: 'darakwonverb_217', japanese: "練る", reading: "ねる", meaning: "반죽하다, 짓이기다", type: 'verb', difficulty: 36, verb_info: '1타' },
        { id: 'darakwonverb_218', japanese: "擦る", reading: "する", meaning: "문지르다, 으깨다, 빻다", type: 'verb', difficulty: 34, verb_info: '1타' },
        { id: 'darakwonverb_219', japanese: "する", reading: "する", meaning: "갈다", type: 'verb', difficulty: 24, verb_info: '1타' },
        { id: 'darakwonverb_220', japanese: "潰す", reading: "つぶす", meaning: "으깨다", type: 'verb', difficulty: 32, verb_info: '1타' },
        { id: 'darakwonverb_221', japanese: "混ぜる", reading: "まぜる", meaning: "서로 섞이게 하다, 뒤섞다", type: 'verb', difficulty: 29, verb_info: '2타' },
        { id: 'darakwonverb_222', japanese: "冷やす", reading: "ひやす", meaning: "차갑게 하다, 식혀서 차게 만들다", type: 'verb', difficulty: 26, verb_info: '1타' },
        { id: 'darakwonverb_223', japanese: "温める", reading: "あたためる", meaning: "데우다", type: 'verb', difficulty: 26, verb_info: '2타' },
        { id: 'darakwonverb_224', japanese: "教える", reading: "おしえる", meaning: "가르치다", type: 'verb', difficulty: 15, verb_info: '2타' },
        { id: 'darakwonverb_225', japanese: "習う", reading: "ならう", meaning: "(기술적으로) 배우다", type: 'verb', difficulty: 18, verb_info: '1타' },
        { id: 'darakwonverb_226', japanese: "学ぶ", reading: "まなぶ", meaning: "(학문적으로) 배우다", type: 'verb', difficulty: 25, verb_info: '1타' },
        { id: 'darakwonverb_227', japanese: "教わる", reading: "おそわる", meaning: "가르침을 받다", type: 'verb', difficulty: 26, verb_info: '1자' },
        { id: 'darakwonverb_228', japanese: "覚える", reading: "おぼえる", meaning: "외우다, 기억하다", type: 'verb', difficulty: 18, verb_info: '2타' },
        { id: 'darakwonverb_229', japanese: "忘れる", reading: "わすれる", meaning: "잊다", type: 'verb', difficulty: 15, verb_info: '2타' },
        { id: 'darakwonverb_230', japanese: "分かる", reading: "わかる", meaning: "(이해로써) 알다", type: 'verb', difficulty: 12, verb_info: '1자' },
        { id: 'darakwonverb_231', japanese: "知る", reading: "しる", meaning: "(지식으로써) 알다", type: 'verb', difficulty: 12, verb_info: '1타' },
        { id: 'darakwonverb_232', japanese: "身に着ける", reading: "みにつける", meaning: "(학문, 기술 등을) 익히다", type: 'verb', difficulty: 32, verb_info: '2타' },
        { id: 'darakwonverb_233', japanese: "サボる", reading: "さぼる", meaning: "게을리 하다", type: 'verb', difficulty: 28, verb_info: '1타' },
        { id: 'darakwonverb_234', japanese: "眺める", reading: "ながめる", meaning: "바라보다", type: 'verb', difficulty: 28, verb_info: '2타' },
        { id: 'darakwonverb_235', japanese: "見える", reading: "みえる", meaning: "보이다", type: 'verb', difficulty: 12, verb_info: '2자' },
        { id: 'darakwonverb_236', japanese: "見せる", reading: "みせる", meaning: "보여주다", type: 'verb', difficulty: 15, verb_info: '2타' },
        { id: 'darakwonverb_237', japanese: "覗く", reading: "のぞく", meaning: "들여다보다, 엿보다", type: 'verb', difficulty: 32, verb_info: '1타' },
        { id: 'darakwonverb_238', japanese: "見付かる", reading: "みつかる", meaning: "발견되다", type: 'verb', difficulty: 28, verb_info: '1자' },
        { id: 'darakwonverb_239', japanese: "見付ける", reading: "みつける", meaning: "눈으로 찾아내다, 발견하다", type: 'verb', difficulty: 22, verb_info: '2타' },
        { id: 'darakwonverb_240', japanese: "聞こえる", reading: "きこえる", meaning: "(소리가) 들리다", type: 'verb', difficulty: 18, verb_info: '2자' },
        { id: 'darakwonverb_241', japanese: "問う", reading: "とう", meaning: "(진리, 책임, 의견을) 묻다", type: 'verb', difficulty: 38, verb_info: '1타' },
        { id: 'darakwonverb_242', japanese: "尋ねる", reading: "たずねる", meaning: "(일상적 정보를 정중하게) 묻다", type: 'verb', difficulty: 24, verb_info: '2타' },
        { id: 'darakwonverb_243', japanese: "答える", reading: "こたえる", meaning: "대답하다", type: 'verb', difficulty: 18, verb_info: '2자' },
        { id: 'darakwonverb_244', japanese: "伝わる", reading: "つたわる", meaning: "전해지다", type: 'verb', difficulty: 26, verb_info: '1자' },
        { id: 'darakwonverb_245', japanese: "伝える", reading: "つたえる", meaning: "전하다", type: 'verb', difficulty: 22, verb_info: '2타' },
        { id: 'darakwonverb_246', japanese: "知らせる", reading: "しらせる", meaning: "알리다", type: 'verb', difficulty: 24, verb_info: '2타' },
        { id: 'darakwonverb_247', japanese: "写す", reading: "うつす", meaning: "베끼다, 사진을 찍다", type: 'verb', difficulty: 28, verb_info: '1타' },
        { id: 'darakwonverb_248', japanese: "載る", reading: "のる", meaning: "게재되다", type: 'verb', difficulty: 34, verb_info: '1자' },
        { id: 'darakwonverb_249', japanese: "載せる", reading: "のせる", meaning: "게재하다", type: 'verb', difficulty: 34, verb_info: '2타' },
        { id: 'darakwonverb_250', japanese: "現れる", reading: "あらわれる", meaning: "모습이 나타나다", type: 'verb', difficulty: 28, verb_info: '2자' },
        { id: 'darakwonverb_251', japanese: "表す", reading: "あらわす", meaning: "표현하다", type: 'verb', difficulty: 33, verb_info: '1타' },
        { id: 'darakwonverb_252', japanese: "現す", reading: "あらわす", meaning: "모습을 드러내다", type: 'verb', difficulty: 36, verb_info: '1타' },
        { id: 'darakwonverb_253', japanese: "著す", reading: "あらわす", meaning: "저술하다", type: 'verb', difficulty: 44, verb_info: '1타' },
        { id: 'darakwonverb_254', japanese: "行く", reading: "いく", meaning: "가다", type: 'verb', difficulty: 10, verb_info: '1자' },
        { id: 'darakwonverb_255', japanese: "来る", reading: "くる", meaning: "오다", type: 'verb', difficulty: 10, verb_info: '3자' },
        { id: 'darakwonverb_256', japanese: "帰る", reading: "かえる", meaning: "귀환하다", type: 'verb', difficulty: 12, verb_info: '1자' },
        { id: 'darakwonverb_257', japanese: "戻る", reading: "もどる", meaning: "되돌아가다", type: 'verb', difficulty: 18, verb_info: '1자' },
        { id: 'darakwonverb_258', japanese: "入る", reading: "はいる", meaning: "들어가다", type: 'verb', difficulty: 12, verb_info: '1자' },
        { id: 'darakwonverb_259', japanese: "入れる", reading: "いれる", meaning: "넣다", type: 'verb', difficulty: 12, verb_info: '2타' },
        { id: 'darakwonverb_260', japanese: "出る", reading: "でる", meaning: "나가다", type: 'verb', difficulty: 12, verb_info: '2자' },
        { id: 'darakwonverb_261', japanese: "出掛ける", reading: "でかける", meaning: "외출하다", type: 'verb', difficulty: 18, verb_info: '2자' },
        { id: 'darakwonverb_262', japanese: "去る", reading: "さる", meaning: "떠나다", type: 'verb', difficulty: 32, verb_info: '1자' },
        { id: 'darakwonverb_263', japanese: "通う", reading: "かよう", meaning: "왕래하다, 통하다", type: 'verb', difficulty: 28, verb_info: '1자' },
        { id: 'darakwonverb_264', japanese: "寄る", reading: "よる", meaning: "들르다, 다가서다", type: 'verb', difficulty: 18, verb_info: '1자' },
        { id: 'darakwonverb_265', japanese: "上がる", reading: "あがる", meaning: "오르다, (집으로) 들어가다, 끝나다", type: 'verb', difficulty: 18, verb_info: '1자' },
        { id: 'darakwonverb_266', japanese: "上げる", reading: "あげる", meaning: "올리다", type: 'verb', difficulty: 15, verb_info: '2타' },
        { id: 'darakwonverb_267', japanese: "上る", reading: "のぼる", meaning: "(계단 등, 단계적으로) 오르다, 달하다", type: 'verb', difficulty: 28, verb_info: '1자' },
        { id: 'darakwonverb_268', japanese: "登る", reading: "のぼる", meaning: "(높이, 노력을 다해) 오르다", type: 'verb', difficulty: 24, verb_info: '1자' },
        { id: 'darakwonverb_269', japanese: "昇る", reading: "のぼる", meaning: "떠오르다, 승진하다", type: 'verb', difficulty: 34, verb_info: '1자' },
        { id: 'darakwonverb_270', japanese: "下る", reading: "くだる", meaning: "(경로를 따라) 내려가다, (명령 등이) 내려지다", type: 'verb', difficulty: 24, verb_info: '1자' },
        { id: 'darakwonverb_271', japanese: "下りる", reading: "おりる", meaning: "(수직적으로) 내려가다, (탈것에서) 내리다", type: 'verb', difficulty: 18, verb_info: '2자' },
        { id: 'darakwonverb_272', japanese: "下がる", reading: "さがる", meaning: "(수치가) 낮아지다", type: 'verb', difficulty: 18, verb_info: '1자' },
        { id: 'darakwonverb_273', japanese: "下げる", reading: "さげる", meaning: "내리다", type: 'verb', difficulty: 18, verb_info: '2타' },
        { id: 'darakwonverb_274', japanese: "落ちる", reading: "おちる", meaning: "떨어지다, 누락되다", type: 'verb', difficulty: 18, verb_info: '2자' },
        { id: 'darakwonverb_275', japanese: "回る", reading: "まわる", meaning: "돌다", type: 'verb', difficulty: 18, verb_info: '1자' },
        { id: 'darakwonverb_276', japanese: "回す", reading: "まわす", meaning: "돌리다", type: 'verb', difficulty: 24, verb_info: '1타' },
        { id: 'darakwonverb_277', japanese: "通る", reading: "とおる", meaning: "지나가다, 널리 알려지다", type: 'verb', difficulty: 22, verb_info: '1자' },
        { id: 'darakwonverb_278', japanese: "通す", reading: "とおす", meaning: "통과시키다, 관철하다", type: 'verb', difficulty: 30, verb_info: '1타' },
        { id: 'darakwonverb_279', japanese: "通じる", reading: "つうじる", meaning: "연결되다, (언어 등이) 통하다", type: 'verb', difficulty: 32, verb_info: '2자' },
        { id: 'darakwonverb_280', japanese: "戻す", reading: "もどす", meaning: "되돌리다", type: 'verb', difficulty: 24, verb_info: '1타' },
        { id: 'darakwonverb_281', japanese: "飛ばす", reading: "とばす", meaning: "날리다, 빨리 몰다, 건너뛰다", type: 'verb', difficulty: 28, verb_info: '1타' },
        { id: 'darakwonverb_282', japanese: "渡す", reading: "わたす", meaning: "건네다, 넘겨주다", type: 'verb', difficulty: 22, verb_info: '1타' },
        { id: 'darakwonverb_283', japanese: "流れる", reading: "ながれる", meaning: "흐르다, 무산되다", type: 'verb', difficulty: 25, verb_info: '2자' },
        { id: 'darakwonverb_284', japanese: "流す", reading: "ながす", meaning: "흘리다, 씻어내다, 퍼뜨리다", type: 'verb', difficulty: 30, verb_info: '1타' },
        { id: 'darakwonverb_285', japanese: "行う", reading: "おこなう", meaning: "실시하다", type: 'verb', difficulty: 32, verb_info: '1타' },
        { id: 'darakwonverb_286', japanese: "倒れる", reading: "たおれる", meaning: "넘어지다, 쓰러지다", type: 'verb', difficulty: 27, verb_info: '2자' },
        { id: 'darakwonverb_287', japanese: "転ぶ", reading: "ころぶ", meaning: "넘어지다, 자빠지다", type: 'verb', difficulty: 28, verb_info: '1자' },
        { id: 'darakwonverb_288', japanese: "滑る", reading: "すべる", meaning: "미끄러지다, 낙방하다", type: 'verb', difficulty: 28, verb_info: '1자' },
        { id: 'darakwonverb_289', japanese: "真似る", reading: "まねる", meaning: "흉내 내다", type: 'verb', difficulty: 26, verb_info: '2타' },
        { id: 'darakwonverb_290', japanese: "囲む", reading: "かこむ", meaning: "둘러싸다", type: 'verb', difficulty: 33, verb_info: '1타' },
        { id: 'darakwonverb_291', japanese: "暴れる", reading: "あばれる", meaning: "난폭하게 행동하다, 난동 피우다", type: 'verb', difficulty: 38, verb_info: '2자' },
        { id: 'darakwonverb_292', japanese: "疲れる", reading: "つかれる", meaning: "지치다", type: 'verb', difficulty: 18, verb_info: '2자' },
        { id: 'darakwonverb_293', japanese: "くたびれる", reading: "くたびれる", meaning: "(구어적) 지치다, 녹초가 되다, 낡아지다", type: 'verb', difficulty: 34, verb_info: '2자' },
        { id: 'darakwonverb_294', japanese: "寛ぐ", reading: "くつろぐ", meaning: "편히 쉬다", type: 'verb', difficulty: 34, verb_info: '1자' },
        { id: 'darakwonverb_295', japanese: "動く", reading: "うごく", meaning: "움직이다", type: 'verb', difficulty: 12, verb_info: '1자' },
        { id: 'darakwonverb_296', japanese: "動かす", reading: "うごかす", meaning: "옮기다, (마음을) 움직이다", type: 'verb', difficulty: 18, verb_info: '1타' },
        { id: 'darakwonverb_297', japanese: "進む", reading: "すすむ", meaning: "나아가다, 진학하다", type: 'verb', difficulty: 18, verb_info: '1자' },
        { id: 'darakwonverb_298', japanese: "止まる", reading: "とまる", meaning: "멈추다", type: 'verb', difficulty: 18, verb_info: '1자' },
        { id: 'darakwonverb_299', japanese: "止める", reading: "とめる", meaning: "멈추게 하다", type: 'verb', difficulty: 18, verb_info: '2타' },
        { id: 'darakwonverb_300', japanese: "張る", reading: "はる", meaning: "덮이다, 팽팽해지다", type: 'verb', difficulty: 34, verb_info: '1자' },
        { id: 'darakwonverb_301', japanese: "張る", reading: "はる", meaning: "펴다, (텐트 등을) 치다, (액체를) 채우다", type: 'verb', difficulty: 30, verb_info: '1타' },
        { id: 'darakwonverb_302', japanese: "浮く", reading: "うく", meaning: "(부양, 바닥과의 분리로서) 뜨다", type: 'verb', difficulty: 28, verb_info: '1자' },
        { id: 'darakwonverb_303', japanese: "浮かぶ", reading: "うかぶ", meaning: "(동작, 현상, 풍경으로서) 뜨다", type: 'verb', difficulty: 28, verb_info: '1자' },
        { id: 'darakwonverb_304', japanese: "浮かべる", reading: "うかべる", meaning: "띄우다", type: 'verb', difficulty: 32, verb_info: '2타' },
        { id: 'darakwonverb_305', japanese: "潜る", reading: "もぐる", meaning: "잠수하다", type: 'verb', difficulty: 30, verb_info: '1자' },
        { id: 'darakwonverb_306', japanese: "片付ける", reading: "かたづける", meaning: "정리하다, 치우다", type: 'verb', difficulty: 20, verb_info: '2타' },
        { id: 'darakwonverb_307', japanese: "整える", reading: "ととのえる", meaning: "정돈하다, 갖추다", type: 'verb', difficulty: 28, verb_info: '2타' },
        { id: 'darakwonverb_308', japanese: "整う", reading: "ととのう", meaning: "정돈되다, 갖추어지다", type: 'verb', difficulty: 28, verb_info: '1자' },
        { id: 'darakwonverb_309', japanese: "直る", reading: "なおる", meaning: "(고장, 잘못, 흐트러짐이) 고쳐지다", type: 'verb', difficulty: 18, verb_info: '1자' },
        { id: 'darakwonverb_310', japanese: "治る", reading: "なおる", meaning: "(병, 상처가) 낫다, 치료되다", type: 'verb', difficulty: 18, verb_info: '1자' },
        { id: 'darakwonverb_311', japanese: "直す", reading: "なおす", meaning: "(고장, 틀린 점을) 고치다, 바로잡다", type: 'verb', difficulty: 18, verb_info: '1타' },
        { id: 'darakwonverb_312', japanese: "治す", reading: "なおす", meaning: "(병, 상처를) 고치다, 치료하다", type: 'verb', difficulty: 20, verb_info: '1타' },
        { id: 'darakwonverb_313', japanese: "受け入れる", reading: "うけいれる", meaning: "상대, 의견, 현실 등을 받아들이다", type: 'verb', difficulty: 28, verb_info: '2타' },
        { id: 'darakwonverb_314', japanese: "受け止める", reading: "うけとめる", meaning: "날아오는 것을 받아내다, 의미나 감정을 받아들이다", type: 'verb', difficulty: 32, verb_info: '2타' },
        { id: 'darakwonverb_315', japanese: "受かる", reading: "うかる", meaning: "합격하다", type: 'verb', difficulty: 24, verb_info: '1자' },
        { id: 'darakwonverb_316', japanese: "落とす", reading: "おとす", meaning: "떨어뜨리다, 빠뜨리다", type: 'verb', difficulty: 18, verb_info: '1타' },
        { id: 'darakwonverb_317', japanese: "落ち込む", reading: "おちこむ", meaning: "침울해지다, 빠지다", type: 'verb', difficulty: 30, verb_info: '1자' },
        { id: 'darakwonverb_318', japanese: "引き出す", reading: "ひきだす", meaning: "끌어내다, 인출하다", type: 'verb', difficulty: 28, verb_info: '1타' },
        { id: 'darakwonverb_319', japanese: "引き返す", reading: "ひきかえす", meaning: "되돌아가다", type: 'verb', difficulty: 28, verb_info: '1자' },
        { id: 'darakwonverb_320', japanese: "引っ込む", reading: "ひっこむ", meaning: "들어가다, 물러나다", type: 'verb', difficulty: 26, verb_info: '1자' },
        { id: 'darakwonverb_321', japanese: "追いかける", reading: "おいかける", meaning: "뒤쫓다", type: 'verb', difficulty: 22, verb_info: '2타' },
        { id: 'darakwonverb_322', japanese: "追い越す", reading: "おいこす", meaning: "추월하다", type: 'verb', difficulty: 28, verb_info: '1타' },
        { id: 'darakwonverb_323', japanese: "追い抜く", reading: "おいぬく", meaning: "앞지르다", type: 'verb', difficulty: 28, verb_info: '1타' },
        { id: 'darakwonverb_324', japanese: "追い込む", reading: "おいこむ", meaning: "몰아넣다", type: 'verb', difficulty: 34, verb_info: '1타' },
        { id: 'darakwonverb_325', japanese: "抜く", reading: "ぬく", meaning: "속에서 뽑다, 빼내다", type: 'verb', difficulty: 22, verb_info: '1타' },
        { id: 'darakwonverb_326', japanese: "抜ける", reading: "ぬける", meaning: "빠지다, 빠져나가다", type: 'verb', difficulty: 22, verb_info: '2자' },
        { id: 'darakwonverb_327', japanese: "泊まる", reading: "とまる", meaning: "숙박하다", type: 'verb', difficulty: 18, verb_info: '1자' },
        { id: 'darakwonverb_328', japanese: "泊める", reading: "とめる", meaning: "묵게 하다", type: 'verb', difficulty: 24, verb_info: '2타' },
        { id: 'darakwonverb_329', japanese: "済む", reading: "すむ", meaning: "끝나다, 해결되다", type: 'verb', difficulty: 18, verb_info: '1자' },
        { id: 'darakwonverb_330', japanese: "済ませる", reading: "すませる", meaning: "끝내다, 해결하다", type: 'verb', difficulty: 24, verb_info: '2타' },
        { id: 'darakwonverb_331', japanese: "支える", reading: "ささえる", meaning: "지탱하다, 떠받치다", type: 'verb', difficulty: 28, verb_info: '2타' },
        { id: 'darakwonverb_332', japanese: "支払う", reading: "しはらう", meaning: "지불하다", type: 'verb', difficulty: 22, verb_info: '1타' },
        { id: 'darakwonverb_333', japanese: "見送る", reading: "みおくる", meaning: "배웅하다, 떠나는 모습을 끝까지 보다", type: 'verb', difficulty: 28, verb_info: '1타' },
        { id: 'darakwonverb_334', japanese: "見直す", reading: "みなおす", meaning: "다시 보다, 재검토하다", type: 'verb', difficulty: 28, verb_info: '1타' },
        { id: 'darakwonverb_335', japanese: "見守る", reading: "みまもる", meaning: "곁에서 계속 지켜보다, 주의 깊게 보다", type: 'verb', difficulty: 30, verb_info: '1타' },
        { id: 'darakwonverb_336', japanese: "見分ける", reading: "みわける", meaning: "구별하다", type: 'verb', difficulty: 34, verb_info: '2타' },
        { id: 'darakwonverb_337', japanese: "見渡す", reading: "みわたす", meaning: "둘러보다", type: 'verb', difficulty: 30, verb_info: '1타' },
        { id: 'darakwonverb_338', japanese: "眩む", reading: "くらむ", meaning: "아찔해지다, 현기증이 나다", type: 'verb', difficulty: 34, verb_info: '1자' },
        { id: 'darakwonverb_339', japanese: "聞き取る", reading: "ききとる", meaning: "알아듣다, 청취하다", type: 'verb', difficulty: 28, verb_info: '1타' },
        { id: 'darakwonverb_340', japanese: "聞き返す", reading: "ききかえす", meaning: "되묻다", type: 'verb', difficulty: 22, verb_info: '1타' },
        { id: 'darakwonverb_341', japanese: "話し合う", reading: "はなしあう", meaning: "의논하다", type: 'verb', difficulty: 24, verb_info: '1자' },
        { id: 'darakwonverb_342', japanese: "言い出す", reading: "いいだす", meaning: "말을 꺼내다", type: 'verb', difficulty: 28, verb_info: '1자' },
        { id: 'darakwonverb_343', japanese: "言い返す", reading: "いいかえす", meaning: "말대꾸하다", type: 'verb', difficulty: 24, verb_info: '1타' },
        { id: 'darakwonverb_344', japanese: "言い換える", reading: "いいかえる", meaning: "바꾸어 말하다", type: 'verb', difficulty: 30, verb_info: '2타' },
        { id: 'darakwonverb_345', japanese: "読み返す", reading: "よみかえす", meaning: "다시 읽다", type: 'verb', difficulty: 24, verb_info: '1타' },
        { id: 'darakwonverb_346', japanese: "読み上げる", reading: "よみあげる", meaning: "소리 내어 읽다", type: 'verb', difficulty: 26, verb_info: '2타' },
        { id: 'darakwonverb_347', japanese: "書き直す", reading: "かきなおす", meaning: "다시 쓰다", type: 'verb', difficulty: 24, verb_info: '1타' },
        { id: 'darakwonverb_348', japanese: "書き留める", reading: "かきとめる", meaning: "적어 두다", type: 'verb', difficulty: 30, verb_info: '2타' },
        { id: 'darakwonverb_349', japanese: "書き込む", reading: "かきこむ", meaning: "써넣다, 입력하다", type: 'verb', difficulty: 28, verb_info: '1타' },
        { id: 'darakwonverb_350', japanese: "考え込む", reading: "かんがえこむ", meaning: "곰곰이 생각하다", type: 'verb', difficulty: 30, verb_info: '1자' },
        { id: 'darakwonverb_351', japanese: "思い出す", reading: "おもいだす", meaning: "생각해내다", type: 'verb', difficulty: 20, verb_info: '1타' },
        { id: 'darakwonverb_352', japanese: "思い込む", reading: "おもいこむ", meaning: "굳게 믿다, 단정하다", type: 'verb', difficulty: 30, verb_info: '1자' },
        { id: 'darakwonverb_353', japanese: "忘れ去る", reading: "わすれさる", meaning: "완전히 잊어버리다", type: 'verb', difficulty: 36, verb_info: '1타' },
        { id: 'darakwonverb_354', japanese: "訳す", reading: "やく", meaning: "번역하다", type: 'verb', difficulty: 28, verb_info: '1타' },
        { id: 'darakwonverb_355', japanese: "比べる", reading: "くらべる", meaning: "비교하다", type: 'verb', difficulty: 20, verb_info: '2타' },
        { id: 'darakwonverb_356', japanese: "例える", reading: "たとえる", meaning: "비유하다", type: 'verb', difficulty: 30, verb_info: '2타' },
        { id: 'darakwonverb_357', japanese: "認める", reading: "みとめる", meaning: "인정하다", type: 'verb', difficulty: 24, verb_info: '2타' },
        { id: 'darakwonverb_358', japanese: "見込む", reading: "みこむ", meaning: "예상하다, 기대하다", type: 'verb', difficulty: 34, verb_info: '1타' },
        { id: 'darakwonverb_359', japanese: "取り上げる", reading: "とりあげる", meaning: "집어 들다, 채택하다", type: 'verb', difficulty: 34, verb_info: '2타' },
        { id: 'darakwonverb_360', japanese: "取り戻す", reading: "とりもどす", meaning: "되찾다", type: 'verb', difficulty: 32, verb_info: '1타' },
        { id: 'darakwonverb_361', japanese: "取り替える", reading: "とりかえる", meaning: "교체하다", type: 'verb', difficulty: 28, verb_info: '2타' },
        { id: 'darakwonverb_362', japanese: "取り替わる", reading: "とりかわる", meaning: "교체되다", type: 'verb', difficulty: 34, verb_info: '1자' },
        { id: 'darakwonverb_363', japanese: "取り組む", reading: "とりくむ", meaning: "맞서다, 몰두하다", type: 'verb', difficulty: 30, verb_info: '1자' },
        { id: 'darakwonverb_364', japanese: "取り寄せる", reading: "とりよせる", meaning: "주문하여 받아오다", type: 'verb', difficulty: 30, verb_info: '2타' },
        { id: 'darakwonverb_365', japanese: "取り外す", reading: "とりはずす", meaning: "떼어내다", type: 'verb', difficulty: 32, verb_info: '1타' },
        { id: 'darakwonverb_366', japanese: "取り巻く", reading: "とりまく", meaning: "둘러싸다", type: 'verb', difficulty: 36, verb_info: '1타' },
        { id: 'darakwonverb_367', japanese: "取り締まる", reading: "とりしまる", meaning: "단속하다", type: 'verb', difficulty: 40, verb_info: '1타' },
        { id: 'darakwonverb_368', japanese: "差し出す", reading: "さしだす", meaning: "내밀다, 제출하다", type: 'verb', difficulty: 26, verb_info: '1타' },
        { id: 'darakwonverb_369', japanese: "差し引く", reading: "さしひく", meaning: "셈해서 빼다, 공제하다", type: 'verb', difficulty: 34, verb_info: '1타' },
        { id: 'darakwonverb_370', japanese: "差し掛かる", reading: "さしかかる", meaning: "이르다, 다다르다", type: 'verb', difficulty: 36, verb_info: '1자' },
        { id: 'darakwonverb_371', japanese: "振り返る", reading: "ふりかえる", meaning: "뒤돌아보다, 되돌아보다", type: 'verb', difficulty: 24, verb_info: '1자' },
        { id: 'darakwonverb_372', japanese: "振り向く", reading: "ふりむく", meaning: "뒤돌아보다", type: 'verb', difficulty: 22, verb_info: '1자' },
        { id: 'darakwonverb_373', japanese: "振り込む", reading: "ふりこむ", meaning: "송금하다", type: 'verb', difficulty: 34, verb_info: '1타' },
        { id: 'darakwonverb_374', japanese: "投げ出す", reading: "なげだす", meaning: "내던지다, 포기하다", type: 'verb', difficulty: 30, verb_info: '1타' },
        { id: 'darakwonverb_375', japanese: "押し付ける", reading: "おしつける", meaning: "강요하다, 밀어붙이다", type: 'verb', difficulty: 34, verb_info: '2타' },
        { id: 'darakwonverb_376', japanese: "押し寄せる", reading: "おしよせる", meaning: "밀려오다", type: 'verb', difficulty: 32, verb_info: '2자' },
        { id: 'darakwonverb_377', japanese: "押し込む", reading: "おしこむ", meaning: "밀어 넣다", type: 'verb', difficulty: 28, verb_info: '1타' },
        { id: 'darakwonverb_378', japanese: "押し切る", reading: "おしきる", meaning: "밀어붙여 해내다", type: 'verb', difficulty: 34, verb_info: '1타' },
        { id: 'darakwonverb_379', japanese: "折り返す", reading: "おりかえす", meaning: "되돌리다, 접어 넘기다", type: 'verb', difficulty: 28, verb_info: '1타' },
        { id: 'darakwonverb_380', japanese: "折り重なる", reading: "おりかさなる", meaning: "겹겹이 포개지다", type: 'verb', difficulty: 38, verb_info: '1자' },
        { id: 'darakwonverb_381', japanese: "駆けつける", reading: "かけつける", meaning: "급히 달려가다", type: 'verb', difficulty: 30, verb_info: '2자' },
        { id: 'darakwonverb_382', japanese: "駆け回る", reading: "かけまわる", meaning: "뛰어다니다", type: 'verb', difficulty: 34, verb_info: '1자' },
        { id: 'darakwonverb_383', japanese: "噛みつく", reading: "かみつく", meaning: "물다, 덤벼들다", type: 'verb', difficulty: 32, verb_info: '1자' },
        { id: 'darakwonverb_384', japanese: "噛み合う", reading: "かみあう", meaning: "맞물리다, 서로 잘 맞다", type: 'verb', difficulty: 32, verb_info: '1자' },
        { id: 'darakwonverb_385', japanese: "かじる", reading: "かじる", meaning: "베어 먹다, 조금 맛보다", type: 'verb', difficulty: 24, verb_info: '1타' },
        { id: 'darakwonverb_386', japanese: "くっつく", reading: "くっつく", meaning: "달라붙다", type: 'verb', difficulty: 20, verb_info: '1자' },
        { id: 'darakwonverb_387', japanese: "くっつける", reading: "くっつける", meaning: "붙이다", type: 'verb', difficulty: 22, verb_info: '2타' },
        { id: 'darakwonverb_388', japanese: "くり抜く", reading: "くりぬく", meaning: "도려내다, 파내다", type: 'verb', difficulty: 38, verb_info: '1타' },
        { id: 'darakwonverb_389', japanese: "くみ取る", reading: "くみとる", meaning: "퍼내다, 헤아리다", type: 'verb', difficulty: 40, verb_info: '1타' },
        { id: 'darakwonverb_390', japanese: "転がる", reading: "ころがる", meaning: "구르다", type: 'verb', difficulty: 20, verb_info: '1자' },
        { id: 'darakwonverb_391', japanese: "転がす", reading: "ころがす", meaning: "굴리다", type: 'verb', difficulty: 24, verb_info: '1타' },
        { id: 'darakwonverb_392', japanese: "転げ落ちる", reading: "ころげおちる", meaning: "굴러 떨어지다", type: 'verb', difficulty: 38, verb_info: '2자' },
        { id: 'darakwonverb_393', japanese: "逆らう", reading: "さからう", meaning: "거역하다", type: 'verb', difficulty: 34, verb_info: '1자' },
        { id: 'darakwonverb_394', japanese: "さびる", reading: "さびる", meaning: "녹슬다", type: 'verb', difficulty: 24, verb_info: '2자' },
        { id: 'darakwonverb_395', japanese: "冷ます", reading: "さます", meaning: "뜨거운 것을 식히다, 흥분을 가라앉히다", type: 'verb', difficulty: 24, verb_info: '1타' },
        { id: 'darakwonverb_396', japanese: "冷める", reading: "さめる", meaning: "식다, 식어 가다", type: 'verb', difficulty: 20, verb_info: '2자' },
        { id: 'darakwonverb_397', japanese: "しくじる", reading: "しくじる", meaning: "실수하다, 실패하다", type: 'verb', difficulty: 36, verb_info: '2자' },
        { id: 'darakwonverb_398', japanese: "しのぐ", reading: "しのぐ", meaning: "견디다, 버텨 넘기다", type: 'verb', difficulty: 38, verb_info: '1타' },
        { id: 'darakwonverb_399', japanese: "しぼり込む", reading: "しぼりこむ", meaning: "압축하다, 추려내다", type: 'verb', difficulty: 40, verb_info: '1타' },
        { id: 'darakwonverb_400', japanese: "すれ違う", reading: "すれちがう", meaning: "스쳐 지나가다", type: 'verb', difficulty: 26, verb_info: '1자' },
        { id: 'darakwonverb_401', japanese: "すり替える", reading: "すりかえる", meaning: "바꿔치기하다", type: 'verb', difficulty: 38, verb_info: '2타' },
        { id: 'darakwonverb_402', japanese: "すり減る", reading: "すりへる", meaning: "닳다", type: 'verb', difficulty: 34, verb_info: '1자' },
        { id: 'darakwonverb_403', japanese: "ずらす", reading: "ずらす", meaning: "비키다, 어긋나게 하다", type: 'verb', difficulty: 24, verb_info: '1타' },
        { id: 'darakwonverb_404', japanese: "迫る", reading: "せまる", meaning: "다가오다, 압박하다", type: 'verb', difficulty: 30, verb_info: '1자' },
        { id: 'darakwonverb_405', japanese: "添える", reading: "そえる", meaning: "곁들이다, 덧붙이다", type: 'verb', difficulty: 26, verb_info: '2타' },
        { id: 'darakwonverb_406', japanese: "備える", reading: "そなえる", meaning: "갖추다, 대비하다", type: 'verb', difficulty: 30, verb_info: '2타' },
        { id: 'darakwonverb_407', japanese: "損なう", reading: "そこなう", meaning: "손상시키다, 해치다", type: 'verb', difficulty: 34, verb_info: '1타' },
        { id: 'darakwonverb_408', japanese: "損ねる", reading: "そこねる", meaning: "놓치다, 그르치다", type: 'verb', difficulty: 38, verb_info: '2타' },
        { id: 'darakwonverb_409', japanese: "揃う", reading: "そろう", meaning: "모이다, 갖추어지다", type: 'verb', difficulty: 24, verb_info: '1자' },
        { id: 'darakwonverb_410', japanese: "揃える", reading: "そろえる", meaning: "가지런히 하다, 갖추다", type: 'verb', difficulty: 24, verb_info: '2타' },
        { id: 'darakwonverb_411', japanese: "蓄える", reading: "たくわえる", meaning: "저축하다, 비축하다", type: 'verb', difficulty: 32, verb_info: '2타' },
        { id: 'darakwonverb_412', japanese: "たどる", reading: "たどる", meaning: "더듬어 가다, 추적하다", type: 'verb', difficulty: 32, verb_info: '1타' },
        { id: 'darakwonverb_413', japanese: "立ち寄る", reading: "たちよる", meaning: "잠시 들르다", type: 'verb', difficulty: 22, verb_info: '1자' },
        { id: 'darakwonverb_414', japanese: "立て替える", reading: "たてかえる", meaning: "대신 지불하다", type: 'verb', difficulty: 36, verb_info: '2타' },
        { id: 'darakwonverb_415', japanese: "立て込む", reading: "たてこむ", meaning: "붐비다, 일이 몰리다", type: 'verb', difficulty: 38, verb_info: '1자' },
        { id: 'darakwonverb_416', japanese: "縮む", reading: "ちぢむ", meaning: "줄어들다, 오그라들다", type: 'verb', difficulty: 24, verb_info: '1자' },
        { id: 'darakwonverb_417', japanese: "縮める", reading: "ちぢめる", meaning: "줄이다, 단축하다", type: 'verb', difficulty: 24, verb_info: '2타' },
        { id: 'darakwonverb_418', japanese: "近づく", reading: "ちかづく", meaning: "가까워지다, 다가가다", type: 'verb', difficulty: 20, verb_info: '1자' },
        { id: 'darakwonverb_419', japanese: "近づける", reading: "ちかづける", meaning: "가깝게 하다, 가까이 대다", type: 'verb', difficulty: 22, verb_info: '2타' },
        { id: 'darakwonverb_420', japanese: "散らかる", reading: "ちらかる", meaning: "어질러지다", type: 'verb', difficulty: 24, verb_info: '1자' },
        { id: 'darakwonverb_421', japanese: "散らかす", reading: "ちらかす", meaning: "어지르다", type: 'verb', difficulty: 24, verb_info: '1타' },
        { id: 'darakwonverb_422', japanese: "散らばる", reading: "ちらばる", meaning: "흩어지다", type: 'verb', difficulty: 24, verb_info: '1자' },
        { id: 'darakwonverb_423', japanese: "散らす", reading: "ちらす", meaning: "흩뜨리다, 흩뿌리다", type: 'verb', difficulty: 22, verb_info: '1타' },
        { id: 'darakwonverb_424', japanese: "つまずく", reading: "つまずく", meaning: "걸려 넘어지다, 좌절하다", type: 'verb', difficulty: 24, verb_info: '1자' },
        { id: 'darakwonverb_425', japanese: "つなぐ", reading: "つなぐ", meaning: "떨어진 것을 이어 붙이다, 연결하다", type: 'verb', difficulty: 20, verb_info: '1타' },
        { id: 'darakwonverb_426', japanese: "つながる", reading: "つながる", meaning: "이어지다, 연결되다", type: 'verb', difficulty: 20, verb_info: '1자' },
        { id: 'darakwonverb_427', japanese: "つり合う", reading: "つりあう", meaning: "서로 균형이 맞다, 조화를 이루다", type: 'verb', difficulty: 34, verb_info: '1자' },
        { id: 'darakwonverb_428', japanese: "つり上げる", reading: "つりあげる", meaning: "끌어올리다, 들어 올리다", type: 'verb', difficulty: 32, verb_info: '2타' },
        { id: 'darakwonverb_429', japanese: "出迎える", reading: "でむかえる", meaning: "마중 나가다", type: 'verb', difficulty: 26, verb_info: '2타' },
        { id: 'darakwonverb_430', japanese: "出会う", reading: "であう", meaning: "만나다, 우연히 마주치다", type: 'verb', difficulty: 20, verb_info: '1자' },
        { id: 'darakwonverb_431', japanese: "出直す", reading: "でなおす", meaning: "다시 오다, 새로 시작하다", type: 'verb', difficulty: 26, verb_info: '1자' },
        { id: 'darakwonverb_432', japanese: "研ぐ", reading: "とぐ", meaning: "갈다, (쌀을) 씻다", type: 'verb', difficulty: 28, verb_info: '1타' },
        { id: 'darakwonverb_433', japanese: "捕らえる", reading: "とらえる", meaning: "붙잡다, 파악하다", type: 'verb', difficulty: 34, verb_info: '2타' },
        { id: 'darakwonverb_434', japanese: "飛び込む", reading: "とびこむ", meaning: "뛰어들다", type: 'verb', difficulty: 22, verb_info: '1자' },
        { id: 'darakwonverb_435', japanese: "飛び出す", reading: "とびだす", meaning: "뛰쳐나가다", type: 'verb', difficulty: 20, verb_info: '1자' },
        { id: 'darakwonverb_436', japanese: "飛び乗る", reading: "とびのる", meaning: "뛰어 타다", type: 'verb', difficulty: 28, verb_info: '1자' },
        { id: 'darakwonverb_437', japanese: "飛び降りる", reading: "とびおりる", meaning: "뛰어내리다", type: 'verb', difficulty: 28, verb_info: '2자' },
        { id: 'darakwonverb_438', japanese: "とぼける", reading: "とぼける", meaning: "시치미 떼다", type: 'verb', difficulty: 34, verb_info: '2자' },
        { id: 'darakwonverb_439', japanese: "溶かす", reading: "とかす", meaning: "녹이다", type: 'verb', difficulty: 28, verb_info: '1타' },
        { id: 'darakwonverb_440', japanese: "溶け込む", reading: "とけこむ", meaning: "주변에 자연스럽게 스며들어 어울리다", type: 'verb', difficulty: 34, verb_info: '1자' },
        { id: 'darakwonverb_441', japanese: "解く", reading: "とく", meaning: "풀다, 해명하다", type: 'verb', difficulty: 24, verb_info: '1타' },
        { id: 'darakwonverb_442', japanese: "どける", reading: "どける", meaning: "치우다, 비키게 하다", type: 'verb', difficulty: 24, verb_info: '2타' },
        { id: 'darakwonverb_443', japanese: "どく", reading: "どく", meaning: "비키다", type: 'verb', difficulty: 20, verb_info: '1자' },
        { id: 'darakwonverb_444', japanese: "取り乱す", reading: "とりみだす", meaning: "허둥대다, 평정을 잃다", type: 'verb', difficulty: 36, verb_info: '1타' },
        { id: 'darakwonverb_445', japanese: "泣き出す", reading: "なきだす", meaning: "울기 시작하다", type: 'verb', difficulty: 20, verb_info: '1자' },
        { id: 'darakwonverb_446', japanese: "投げ込む", reading: "なげこむ", meaning: "내던지다, 투입하다", type: 'verb', difficulty: 30, verb_info: '1타' },
        { id: 'darakwonverb_447', japanese: "慣らす", reading: "ならす", meaning: "익숙하게 하다", type: 'verb', difficulty: 28, verb_info: '1타' },
        { id: 'darakwonverb_448', japanese: "匂う", reading: "におう", meaning: "냄새가 나다", type: 'verb', difficulty: 18, verb_info: '1자' },
        { id: 'darakwonverb_449', japanese: "塗り替える", reading: "ぬりかえる", meaning: "새로 칠하다", type: 'verb', difficulty: 34, verb_info: '2타' },
        { id: 'darakwonverb_450', japanese: "ぬらす", reading: "ぬらす", meaning: "적시다", type: 'verb', difficulty: 20, verb_info: '1타' },
        { id: 'darakwonverb_451', japanese: "乗り越える", reading: "のりこえる", meaning: "넘어서다, 극복하다", type: 'verb', difficulty: 30, verb_info: '2타' },
        { id: 'darakwonverb_452', japanese: "伸びる", reading: "のびる", meaning: "늘어나다, 자라다", type: 'verb', difficulty: 18, verb_info: '2자' },
        { id: 'darakwonverb_453', japanese: "伸ばす", reading: "のばす", meaning: "늘리다, 뻗다", type: 'verb', difficulty: 20, verb_info: '1타' },
        { id: 'darakwonverb_454', japanese: "のめり込む", reading: "のめりこむ", meaning: "깊이 빠져들다", type: 'verb', difficulty: 38, verb_info: '1자' },
        { id: 'darakwonverb_455', japanese: "映す", reading: "うつす", meaning: "비추다, 반영하다", type: 'verb', difficulty: 30, verb_info: '1타' },
        { id: 'darakwonverb_456', japanese: "映る", reading: "うつる", meaning: "비치다, 반영되다", type: 'verb', difficulty: 28, verb_info: '1자' },
        { id: 'darakwonverb_457', japanese: "はがす", reading: "はがす", meaning: "벗기다, 떼어 내다", type: 'verb', difficulty: 24, verb_info: '1타' },
        { id: 'darakwonverb_458', japanese: "はがれる", reading: "はがれる", meaning: "벗겨지다, 떨어지다", type: 'verb', difficulty: 24, verb_info: '2자' },
        { id: 'darakwonverb_459', japanese: "はずむ", reading: "はずむ", meaning: "튀다, 들뜨다", type: 'verb', difficulty: 26, verb_info: '1자' },
        { id: 'darakwonverb_460', japanese: "はみ出す", reading: "はみだす", meaning: "삐져나오다, 벗어나다", type: 'verb', difficulty: 28, verb_info: '1자' },
        { id: 'darakwonverb_461', japanese: "払い戻す", reading: "はらいもどす", meaning: "환불하다", type: 'verb', difficulty: 38, verb_info: '1타' },
        { id: 'darakwonverb_462', japanese: "引き止める", reading: "ひきとめる", meaning: "만류하다, 붙잡다", type: 'verb', difficulty: 32, verb_info: '2타' },
        { id: 'darakwonverb_463', japanese: "引き抜く", reading: "ひきぬく", meaning: "뽑아내다, 빼내다", type: 'verb', difficulty: 34, verb_info: '1타' },
        { id: 'darakwonverb_464', japanese: "引き寄せる", reading: "ひきよせる", meaning: "끌어당기다", type: 'verb', difficulty: 30, verb_info: '2타' },
        { id: 'darakwonverb_465', japanese: "引きずる", reading: "ひきずる", meaning: "질질 끌다, 오래 끌다", type: 'verb', difficulty: 26, verb_info: '1타' },
        { id: 'darakwonverb_466', japanese: "広がる", reading: "ひろがる", meaning: "퍼지다, 넓어지다", type: 'verb', difficulty: 18, verb_info: '1자' },
        { id: 'darakwonverb_467', japanese: "広げる", reading: "ひろげる", meaning: "펼치다, 넓히다", type: 'verb', difficulty: 18, verb_info: '2타' },
        { id: 'darakwonverb_468', japanese: "深まる", reading: "ふかまる", meaning: "깊어지다", type: 'verb', difficulty: 30, verb_info: '1자' },
        { id: 'darakwonverb_469', japanese: "深める", reading: "ふかめる", meaning: "깊게 하다", type: 'verb', difficulty: 30, verb_info: '2타' },
        { id: 'darakwonverb_470', japanese: "ふくらむ", reading: "ふくらむ", meaning: "부풀다", type: 'verb', difficulty: 24, verb_info: '1자' },
        { id: 'darakwonverb_471', japanese: "ふくらませる", reading: "ふくらませる", meaning: "부풀리다", type: 'verb', difficulty: 28, verb_info: '2타' },
        { id: 'darakwonverb_472', japanese: "ふるえる", reading: "ふるえる", meaning: "떨리다", type: 'verb', difficulty: 18, verb_info: '2자' },
        { id: 'darakwonverb_473', japanese: "へこむ", reading: "へこむ", meaning: "움푹 패다, 풀이 죽다", type: 'verb', difficulty: 24, verb_info: '1자' },
        { id: 'darakwonverb_474', japanese: "へらす", reading: "へらす", meaning: "줄이다", type: 'verb', difficulty: 18, verb_info: '1타' },
        { id: 'darakwonverb_475', japanese: "ほぐす", reading: "ほぐす", meaning: "엉킨 것이나 굳은 것을 풀다, 느슨하게 하다", type: 'verb', difficulty: 30, verb_info: '1타' },
        { id: 'darakwonverb_476', japanese: "ほぐれる", reading: "ほぐれる", meaning: "엉킨 것이나 긴장이 풀리다, 누그러지다", type: 'verb', difficulty: 30, verb_info: '2자' },
        { id: 'darakwonverb_477', japanese: "ほどく", reading: "ほどく", meaning: "(매듭, 끈 등을) 풀다", type: 'verb', difficulty: 24, verb_info: '1타' },
        { id: 'darakwonverb_478', japanese: "ほどける", reading: "ほどける", meaning: "(매듭, 끈 등이) 풀리다", type: 'verb', difficulty: 24, verb_info: '2자' },
        { id: 'darakwonverb_479', japanese: "まかなう", reading: "まかなう", meaning: "마련하다, 충당하다", type: 'verb', difficulty: 36, verb_info: '1타' },
        { id: 'darakwonverb_480', japanese: "交わる", reading: "まじわる", meaning: "교차하다, 사귀다", type: 'verb', difficulty: 36, verb_info: '1자' },
        { id: 'darakwonverb_481', japanese: "交える", reading: "まじえる", meaning: "서로 섞다, 사이에 끼워 넣다", type: 'verb', difficulty: 32, verb_info: '2타' },
        { id: 'darakwonverb_482', japanese: "混じる", reading: "まじる", meaning: "섞이다", type: 'verb', difficulty: 24, verb_info: '1자' },
        { id: 'darakwonverb_483', japanese: "まとめる", reading: "まとめる", meaning: "정리하다, 종합하다", type: 'verb', difficulty: 22, verb_info: '2타' },
        { id: 'darakwonverb_484', japanese: "丸める", reading: "まるめる", meaning: "둥글게 말다, 둥글리다", type: 'verb', difficulty: 24, verb_info: '2타' },
        { id: 'darakwonverb_485', japanese: "満たす", reading: "みたす", meaning: "채우다, 만족시키다", type: 'verb', difficulty: 30, verb_info: '1타' },
        { id: 'darakwonverb_486', japanese: "満ちる", reading: "みちる", meaning: "차다, 가득 차다", type: 'verb', difficulty: 24, verb_info: '1자' },
        { id: 'darakwonverb_487', japanese: "むしる", reading: "むしる", meaning: "쥐어뜯다, 뽑아내다", type: 'verb', difficulty: 28, verb_info: '1타' },
        { id: 'darakwonverb_488', japanese: "めくれる", reading: "めくれる", meaning: "젖혀지다, 들리다", type: 'verb', difficulty: 24, verb_info: '2자' },
        { id: 'darakwonverb_489', japanese: "燃やす", reading: "もやす", meaning: "태우다", type: 'verb', difficulty: 24, verb_info: '1타' },
        { id: 'darakwonverb_490', japanese: "盛る", reading: "もる", meaning: "담다, 쌓아 올리다", type: 'verb', difficulty: 28, verb_info: '1타' },
        { id: 'darakwonverb_491', japanese: "漏らす", reading: "もらす", meaning: "새게 하다, 누설하다", type: 'verb', difficulty: 30, verb_info: '1타' },
        { id: 'darakwonverb_492', japanese: "持ち上げる", reading: "もちあげる", meaning: "들어 올리다, 치켜세우다", type: 'verb', difficulty: 30, verb_info: '2타' },
        { id: 'darakwonverb_493', japanese: "もてなす", reading: "もてなす", meaning: "대접하다", type: 'verb', difficulty: 34, verb_info: '1타' },
        { id: 'darakwonverb_494', japanese: "もみ消す", reading: "もみけす", meaning: "무마하다, 없던 일로 하다", type: 'verb', difficulty: 42, verb_info: '1타' },
        { id: 'darakwonverb_495', japanese: "もむ", reading: "もむ", meaning: "주무르다, 문지르다", type: 'verb', difficulty: 26, verb_info: '1타' },
        { id: 'darakwonverb_496', japanese: "やり直す", reading: "やりなおす", meaning: "다시 하다", type: 'verb', difficulty: 24, verb_info: '1타' },
        { id: 'darakwonverb_497', japanese: "やり遂げる", reading: "やりとげる", meaning: "끝까지 해내다", type: 'verb', difficulty: 32, verb_info: '2타' },
        { id: 'darakwonverb_498', japanese: "やり過ごす", reading: "やりすごす", meaning: "그냥 넘기다", type: 'verb', difficulty: 36, verb_info: '1타' },
        { id: 'darakwonverb_499', japanese: "やわらげる", reading: "やわらげる", meaning: "완화하다", type: 'verb', difficulty: 34, verb_info: '2타' },
        { id: 'darakwonverb_500', japanese: "揺らす", reading: "ゆらす", meaning: "흔들리게 하다, 흔들어 움직이게 하다", type: 'verb', difficulty: 24, verb_info: '1타' }
    ]
});
